# Copyright (c) 2026, Peng Chen, Georgia Institute of Technology.
# This file is part of hIPPyMFEM, free software under the GNU General Public
# License version 2.0 dated June 1991 (GPL-2.0-only); see the files LICENSE and
# COPYRIGHT.
"""Element kernels generated by automatic differentiation.

The user supplies a **pointwise residual density**

.. code-block:: python

    def pde_varf(u, m, p, x):
        return jnp.exp(m.val) * inner(u.grad, p.grad) - f(x) * p.val

where ``u``, ``m``, ``p`` are :class:`Field` records carrying ``val`` and
``grad`` at one quadrature point, and ``x`` is that point's physical position.
It plays the role a UFL form plays in a form-language library: it is the weak
residual of the forward problem, read as the PDE part of the Lagrangian.

:class:`QuadratureKernel` turns it into element-level arrays:

==================================  ===========================================
``grad_block(i)``                   element vectors ``dR/d(dofs_i)``
``hess_block(i, j)``                element matrices ``d2R/d(dofs_i)d(dofs_j)``
``third_block(i, j, k)``            element vectors, ``d3R`` contracted with two
                                    given directions
==================================  ===========================================

with ``i`` a field slot.  For the stationary problem those are exactly the blocks a
form-language library obtains from ``ufl.derivative``: ``hess_block(ADJOINT, STATE)``
is the forward Jacobian ``A``, ``hess_block(ADJOINT, PARAMETER)`` is ``C``,
``hess_block(STATE, STATE)`` is ``W_uu``, and so on.

Because every block is differentiated from one quadrature sum, all of them are
consistent with each other and with the same integration rule, which is what
makes the adjoint gradient exact for the discretized problem rather than merely
close.
"""

import functools
import os
import time
import warnings
from typing import NamedTuple

import numpy as np

from .. import _jaxconfig                         # noqa: F401
from ..common.mpiutil import local_rank

# Device and precision defaults live in hippymfem._jaxconfig, which must be
# imported before jax; see that module for why the default platform is the CPU.
import jax                                        # noqa: E402
import jax.numpy as jnp                           # noqa: E402

jax.config.update("jax_enable_x64", True)


#: Precision the differentiated element kernels compute in.  Set ``HIPPYMFEM_PRECISION``.
#:
#: ``"fp64"``
#:     Everything in double precision.  The default.
#: ``"mixed"``
#:     The element **matrices** (the Jacobian and the Hessian blocks) are computed in
#:     single precision; the element **vectors** (residuals, gradients, the products
#:     of the matrix-free mode) and the values stay in double.  hypre still gets
#:     double-precision matrices, whose entries are then accurate to about 1e-7.  The
#:     forward and the adjoint solve correct for that by iterative refinement against
#:     the double-precision residual (:class:`~hippymfem.modeling.PDEVariationalProblem`),
#:     so the state, the adjoint, the cost and the gradient are those of ``"fp64"`` to
#:     the tolerance of the solves; what is perturbed, at 1e-7, is the Hessian, which
#:     an inexact Newton-CG method does not notice.  This is the mode to use on GPUs
#:     whose double-precision arithmetic is slow (L40S, RTX-class cards), where the
#:     matrix kernels are several times faster in single precision.
#: ``"fp32"``
#:     Matrices and vectors in single precision: the kernel's inputs are cast inside
#:     the functional every derivative is built on.  Nothing corrects the result, so
#:     residuals stall at about 1e-6 of their size and the reduced gradient is off by
#:     1e-4 to 1e-3 in relative terms; the tolerances that would be unreachable are
#:     raised (:func:`residual_floor`).  A tool for a preconditioner or a rough
#:     solve; ``"mixed"`` costs nearly the same and loses nothing.
#:
#: ``benchmarks/bench_precision.py`` measures the three.
PRECISION = os.environ.get("HIPPYMFEM_PRECISION", "fp64").strip().lower()
_PRECISIONS = ("fp64", "mixed", "fp32")
if PRECISION not in _PRECISIONS:
    raise ValueError("HIPPYMFEM_PRECISION must be one of %s, got %r" % (_PRECISIONS, PRECISION))


def matrix_precision():
    """``"fp32"`` when the element matrices are computed in single precision."""
    return "fp32" if PRECISION in ("fp32", "mixed") else "fp64"


def vector_precision():
    """``"fp32"`` when the element vectors and values are computed in single precision."""
    return "fp32" if PRECISION == "fp32" else "fp64"


#: relative accuracy of a quantity computed by a single-precision kernel
FP32_EPS = 1.2e-7


def residual_floor():
    """The relative size below which an assembled residual cannot be driven with the
    present precision of the element vectors: a tolerance below it is unreachable."""
    return 1e-5 if vector_precision() == "fp32" else 0.0


def gradient_floor():
    """The relative size below which the norm of a reduced gradient cannot be driven when
    the element vectors are in single precision: the state, the adjoint and the gradient
    are then computed to about that accuracy (more on a fine mesh, where the errors of the
    two solves grow with the condition number), and an optimizer that asks for less ends
    in a line search that cannot find a decrease.  Zero in double precision and in the
    mixed mode."""
    return 1e-4 if vector_precision() == "fp32" else 0.0


def matrix_tolerance(tol, single=1e-5):
    """A tolerance for a comparison that involves assembled element matrices: ``tol`` when
    they are computed in double precision.  In single precision an entry carries a relative
    error near ``FP32_EPS`` and a product with the matrix somewhat more, by cancellation,
    so that no such comparison holds tighter than ``single``."""
    return max(float(tol), float(single)) if matrix_precision() == "fp32" else float(tol)


def set_precision(mode):
    """Choose the element-kernel precision (``"fp64"``, ``"mixed"`` or ``"fp32"``, see
    :data:`PRECISION`); returns the old value.

    Clears the compiled-kernel cache of every kernel built so far, since the dtype is
    baked into the jitted code.
    """
    global PRECISION
    if mode not in _PRECISIONS:
        raise ValueError("precision must be one of %s, got %r" % (_PRECISIONS, mode))
    old, PRECISION = PRECISION, mode
    for k in _KERNELS:
        k._cache.clear()
        k._chunk.clear()
    return old


#: Every kernel built, so :func:`set_precision` can invalidate their compiled code.
_KERNELS = []

#: How the element Hessian blocks are differentiated.  ``element`` (the default)
#: pushes one forward tangent per element dof of the column slot through the whole
#: element.  ``quadrature`` differentiates the density twice at each point, with respect
#: to the fields' values and gradients (one tangent per such feature), skips the parts
#: of that pointwise Hessian that are identically zero, and contracts the rest with the
#: basis values and physical gradients; it is exact too, since the fields are linear in
#: the dofs.  On a GPU it is the faster route from P2 up: a Jacobian 1.6x (Poisson, P2
#: tetrahedra) to 4.4x (elasticity, Q2 hexahedra) faster on an L40S, a whole
#: linearization point 1.2x to 1.7x.  On P1 the element route stays the faster (the
#: quadrature route's Jacobian runs at 0.7x), and so it does on the host, except for
#: vector-valued Jacobians (1.4x there).  ``auto`` times both once per kernel program,
#: column slot and device and keeps the faster (:data:`_ROUTES`), so every kernel built
#: alike takes the same route in a run, while which one a run takes, and its round-off,
#: can differ from run to run.  Spaces with a Piola map and interior facets always take
#: the element route.  Set ``HIPPYMFEM_HESSIAN`` or :func:`set_hessian_mode`.
HESSIAN_MODE = os.environ.get("HIPPYMFEM_HESSIAN", "element").strip().lower() or "element"
if HESSIAN_MODE not in ("element", "quadrature", "auto"):
    warnings.warn("HIPPYMFEM_HESSIAN=%r is not element, quadrature or auto; using element"
                  % (HESSIAN_MODE,), RuntimeWarning)
    HESSIAN_MODE = "element"


#: What ``auto`` chose, per kernel program (the density, the slots' shapes, the element
#: and point counts, the precision, the column slot) and device.  Kept here rather than
#: with a kernel's compiled code, so a cleared cache does not time again and every
#: kernel built alike (two problems on one mesh, say) takes the same route and gives the
#: same bits.  Keyed on the density's ``id``: a reused id costs at worst a slower route,
#: never a wrong result.
_ROUTES = {}


def set_hessian_mode(mode):
    """Choose how element Hessians are differentiated (:data:`HESSIAN_MODE`); returns
    the old mode.  Clears every kernel's compiled Hessians."""
    global HESSIAN_MODE
    mode = str(mode).strip().lower()
    if mode not in ("element", "quadrature", "auto"):
        raise ValueError("hessian mode must be element, quadrature or auto, got %r" % (mode,))
    old, HESSIAN_MODE = HESSIAN_MODE, mode
    for k in _KERNELS:
        for key in [key for key in k._cache if key and key[0] in ("hs", "h", "hcols")]:
            del k._cache[key]
    return old


def _as32(tree):
    """Cast every floating array in ``tree`` to float32, leaving integers alone."""
    return jax.tree_util.tree_map(
        lambda a: (a.astype(jnp.float32)
                   if hasattr(a, "dtype") and jnp.issubdtype(a.dtype, jnp.floating)
                   else a),
        tree)


_DEVICE = None


def set_device(kind="cpu", index=None, comm=None):
    """Choose where element kernels run.

    Parameters
    ----------
    kind : {"cpu", "gpu", "cuda", None}
        ``None`` resets to the default.  Asking for a GPU requires
        ``HIPPYMFEM_DEVICE=gpu`` or ``auto`` (or ``JAX_PLATFORMS=cuda``) in the
        environment *before* hippymfem is imported, because JAX reads the platform
        list once.
    index : int, optional
        Which device.  The default assigns **one GPU per MPI rank** by the rank's
        index within its node, so the ranks of a job do not all land on device 0.
    comm : mpi4py communicator, optional
        Used for the node-local rank; defaults to ``COMM_WORLD``.

    Returns the chosen device.
    """
    global _DEVICE
    if kind is None:
        _DEVICE = None
        return None
    if kind in ("gpu", "cuda", "rocm"):
        try:
            devs = jax.devices("cuda")
        except RuntimeError:
            devs = [d for d in jax.devices() if d.platform == "gpu"]
        if not devs:
            raise RuntimeError(
                "no GPU visible to JAX: set HIPPYMFEM_DEVICE=gpu (or "
                "JAX_PLATFORMS=cuda) before importing hippymfem; JAX reads the "
                "platform list once, at import")
    else:
        devs = jax.devices(kind)
    if index is None:
        index = _node_rank(comm) % len(devs)
    _DEVICE = devs[int(index) % len(devs)]
    return _DEVICE


def _node_rank(comm=None):
    """This rank's index within its node, **without a collective when possible**.

    :func:`device` resolves the device on first use, and a rank's first use may
    be somewhere its neighbours never reach (a boundary pattern it owns no element
    of), so a collective here could deadlock.  The launcher's variables answer
    without communicating; the collective
    (:func:`~hippymfem.common.mpiutil.local_rank`) is the fallback for a job that
    named no local rank, and :class:`QuadratureKernel` resolves the device when it
    is built, which every rank does together.
    """
    rank, _, known = _jaxconfig._node()
    return rank if known else local_rank(comm)


def device():
    """The device element kernels run on.

    Honors ``HIPPYMFEM_DEVICE=gpu`` (and ``auto``, a GPU when the process can see
    one) on first use, so a script only has to set the environment variable;
    ``set_device`` overrides it.
    """
    global _DEVICE
    if _DEVICE is None:
        if _jaxconfig.gpu_requested():
            try:
                return set_device("gpu")
            except RuntimeError:
                pass
        try:
            _DEVICE = jax.devices("cpu")[0]
        except RuntimeError:
            _DEVICE = jax.devices()[0]
    return _DEVICE


def on_gpu():
    """True when element kernels are running on a GPU."""
    return device().platform in ("gpu", "cuda", "rocm")


def _put(x):
    if isinstance(x, jax.Array):
        # already a JAX array (the dof values a space hands over from MFEM's device
        # memory, :meth:`~hippymfem.fem.spaces.FunctionSpace.local_values`): no trip
        # through numpy, and no transfer when it is on this device
        return jax.device_put(x, device())
    return jax.device_put(np.ascontiguousarray(x), device())


#: Device copies of the arrays every kernel on a group reads (the group's geometry,
#: the tables of a space on it), one per (owner, attribute, device): the kernels of a
#: problem, of its objective and of a penalty over the same mesh share them instead of
#: holding a copy each (for an optimization-under-uncertainty problem with its QoI, a
#: second copy of the geometry was the largest array on the device).  Keyed on the
#: owner's identity, so an entry goes with its owner.
_SHARED_DEVICE = None


def _shared_put(owner, key, array):
    """``array``, an array of ``owner`` named ``key``, on the current device: the copy
    every kernel shares."""
    global _SHARED_DEVICE
    if _SHARED_DEVICE is None:
        from ..common.identitycache import IdentityCache

        _SHARED_DEVICE = IdentityCache()
    d = device()
    got = _SHARED_DEVICE.get((owner,), extra=(key, d))
    if got is None:
        got = _SHARED_DEVICE.put((owner,), _put(array), extra=(key, d))
    return got


@jax.jit
def gather_rows(values, idx, signs=None):
    """``values[idx]`` (times ``signs``), compiled.

    The element dof gather of every assembly.  Eager indexing normalizes and checks the
    index array with separate array operations at every call, and at 1.6e6 tetrahedra
    it took 0.10 s a slot against 0.0036 s compiled; a gather and a sign flip are
    exact, so the values are the same.
    """
    vals = values[idx]
    return vals if signs is None else vals * signs


def to_host(x):
    """A numpy view/copy of a kernel result, wherever it lives."""
    return np.asarray(x)


def all_finite(arrays):
    """Whether every entry of every array is finite, checked where the data lives.

    Reducing on the device first means one scalar comes back instead of the whole
    element array, which matters because this is called on every assembly.
    """
    ok = True
    for a in arrays:
        if isinstance(a, np.ndarray):
            ok = ok and bool(np.isfinite(a).all())
        else:
            ok = ok and bool(jnp.isfinite(a).all())
        if not ok:
            break
    return ok


class Field(NamedTuple):
    """A field at one quadrature point.

    ``val`` is a scalar for ``vdim == 1`` and shape ``(vdim,)`` otherwise;
    ``grad`` is ``(sdim,)`` or ``(vdim, sdim)`` correspondingly.  It is a
    NamedTuple so ``jax.vmap`` can map over quadrature points transparently.
    """

    val: jnp.ndarray
    grad: jnp.ndarray


def _eval_field(dofs, N, G, Jinv, vdim, nd):
    """Values and physical gradients at every quadrature point of one element.

    ``dofs`` is component-major ``(vdim*nd,)``, matching MFEM's vdof layout.
    """
    V = dofs.reshape(vdim, nd)
    val = jnp.einsum("qi,ci->qc", N, V)                 # (nq, vdim)
    gref = jnp.einsum("qik,ci->qck", G, V)              # (nq, vdim, dim)
    gphys = jnp.einsum("qck,qkd->qcd", gref, Jinv)      # (nq, vdim, sdim)
    if vdim == 1:
        return Field(val[:, 0], gphys[:, 0, :])
    return Field(val, gphys)


#: Largest number of elements handed to one kernel launch.  ``0``, the default,
#: plans the size from the device's free memory (the whole group on the host) and
#: shrinks it on an out-of-memory error; a fixed size would cost extra launches on
#: every problem to protect the few that need it.  Set ``HIPPYMFEM_ELEMENT_CHUNK``
#: to pin a size.
ELEMENT_CHUNK = int(os.environ.get("HIPPYMFEM_ELEMENT_CHUNK", "0") or 0)

#: Doubles of device working set per (tangent, quadrature point) pair, used to size
#: a chunk before the first launch.  Forward-mode AD carries ``nd_total`` tangents
#: through ``nq`` points; measured between 7 and 13 across element types, so 16
#: leaves margin.  Raising it makes chunks smaller and safer.
AD_DOUBLES_PER_TANGENT_QP = float(
    os.environ.get("HIPPYMFEM_AD_WORKING_SET", "16"))

#: Share of JAX's device budget above which a split batch keeps its per-element
#: geometry (``Jinv``, ``wdet``, ``X``) on the host and transfers it a chunk at a
#: time.  Below it the geometry is cached on the device: streaming a small
#: geometry costs transfers for nothing, while caching one that is most of the
#: budget is what runs a chunked Jacobian out of memory.  ``0`` never streams.  Set
#: ``HIPPYMFEM_GEOMETRY_STREAM``.
GEOMETRY_STREAM_FRACTION = float(
    os.environ.get("HIPPYMFEM_GEOMETRY_STREAM", "0.25") or 0)


#: Device memory, in GiB, kept aside for whatever else shares the card (above all
#: hypre's matrices and multigrid hierarchy).  The chunk planner subtracts it from
#: its budget: an adaptive counterpart of the import-time
#: ``HIPPYMFEM_GPU_MEM_FRACTION``.  Set ``HIPPYMFEM_GPU_MEM_RESERVE``.
GPU_MEM_RESERVE = float(os.environ.get("HIPPYMFEM_GPU_MEM_RESERVE", "0") or 0.0)

#: Share of the node's *available* memory one rank may plan a chunk against on the
#: host, the whole node's figure divided by the ranks sharing it.  Without this the
#: host planner has no budget at all (it asks the card, and there is none), so a rank
#: takes its whole element group in one launch; that is right until the group is large,
#: and at 524288 P2 hexahedra a rank it is what the OOM killer ends.  Half is left to
#: hypre, the matrices and everything outside the kernel, which is the same split the
#: device path makes.  ``0`` restores the unplanned host behaviour.  Set
#: ``HIPPYMFEM_HOST_MEM_FRACTION``.
HOST_MEM_FRACTION = float(os.environ.get("HIPPYMFEM_HOST_MEM_FRACTION", "0.5") or 0.0)

#: How a split batch's chunk is sized.  ``estimate``, the default, is the per-tangent
#: estimate of :meth:`GroupKernel._plan`.  ``xla`` asks the compiled program instead:
#: XLA's memory analysis of the pass at a probe chunk gives the argument, output and
#: scratch bytes it needs, which are linear in the chunk, and the chunk is sized to
#: :data:`CHUNK_SHARE` of the free budget from that, never below the estimate.  The
#: estimate is generous (664 kB an element for a P2 hexahedral Hessian pass, where XLA
#: reports 143), so ``xla`` runs far fewer chunks, and fewer chunks buy little: at a
#: million P2 hexahedra on one L40S, hypre on the card, it took the Jacobian pass from 125
#: chunks to 15 and a Hessian pass from 86 to 5, a warm linearization point from 6.9 s to
#: 6.5, the cold one from 13.2 s to 13.6, and JAX's peak from 6.1 GiB to 14.4 (the card's
#: from 24.0 GB to 32.2).  A launch costs about 5 ms there; the element work is the cost.
#: So ``xla`` is for a card with memory to spare.  Set ``HIPPYMFEM_CHUNK_PLAN``.
CHUNK_PLAN = os.environ.get("HIPPYMFEM_CHUNK_PLAN", "estimate").strip().lower()
#: Share of the free budget an analysed chunk may take.  The rest covers what the
#: analysis does not see: the allocator's fragmentation and the scatter's own buffers.
#: Set ``HIPPYMFEM_CHUNK_SHARE``.
CHUNK_SHARE = float(os.environ.get("HIPPYMFEM_CHUNK_SHARE", "0.6") or 0.6)
#: Elements in the probe chunk the analysis is compiled at.  The per-element cost is
#: constant from about 2048 elements up; the probe executable is compiled for that
#: shape only and is not run.
CHUNK_PROBE = int(os.environ.get("HIPPYMFEM_CHUNK_PROBE", "2048") or 2048)

_GPURT = None


def _gpu_free_bytes():
    """Free memory on this process's device, from the vendor's runtime, or None.

    JAX's own statistics are the better source when it has a budget, but an
    allocator that reports none (``XLA_PYTHON_CLIENT_ALLOCATOR=platform``) would
    leave the planner nothing to plan against.  The runtime always knows.  NVIDIA's
    ``cudaMemGetInfo`` and AMD's ``hipMemGetInfo`` have the same signature, and the
    first runtime that answers is kept.
    """
    global _GPURT

    import ctypes

    free, total = ctypes.c_size_t(), ctypes.c_size_t()
    if _GPURT is None:
        # Not the first that loads: an AMD node can carry the CUDA runtime too
        # (JAX's CUDA wheels), which loads and then fails.
        _GPURT = False
        for name, fn in (("libcudart.so", "cudaMemGetInfo"), ("libcudart.so.12", "cudaMemGetInfo"),
                         ("libcudart.so.11.0", "cudaMemGetInfo"), ("libamdhip64.so", "hipMemGetInfo"),
                         ("libamdhip64.so.7", "hipMemGetInfo"), ("libamdhip64.so.6", "hipMemGetInfo")):
            try:
                f = getattr(ctypes.CDLL(name), fn)
                if f(ctypes.byref(free), ctypes.byref(total)) == 0:
                    _GPURT = f
                    return int(free.value)
            except Exception:                           # noqa: BLE001
                continue
        return None
    if not _GPURT:
        return None
    try:
        if _GPURT(ctypes.byref(free), ctypes.byref(total)) != 0:
            return None
    except Exception:                                   # noqa: BLE001
        return None
    return int(free.value)


def _node_ranks():
    """Ranks sharing this node, from the launcher, or 1.

    Read from the environment rather than from MPI, because the planner is not a
    collective and splitting a communicator inside it would deadlock the ranks that
    plan a chunk at a different moment.
    """
    for var in ("OMPI_COMM_WORLD_LOCAL_SIZE", "MV2_COMM_WORLD_LOCAL_SIZE",
                "MPI_LOCALNRANKS", "PMI_LOCAL_SIZE", "SLURM_NTASKS_PER_NODE"):
        try:
            n = int(os.environ.get(var, "") or 0)
        except ValueError:
            continue
        if n > 0:
            return n
    return 1


def _host_free_bytes():
    """This rank's share of the node's available memory, or None.

    ``MemAvailable`` is what the kernel says can be handed out without swapping,
    which is the figure that matters here; it is divided by the ranks on the node,
    since each of them is about to plan its own chunk.
    """
    if HOST_MEM_FRACTION <= 0:
        return None
    try:
        with open("/proc/meminfo") as fh:
            for line in fh:
                if line.startswith("MemAvailable:"):
                    available = float(line.split()[1]) * 1024.0
                    break
            else:
                return None
    except OSError:
        return None
    return int(available * HOST_MEM_FRACTION / max(_node_ranks(), 1))


def _free_budget(d):
    """Bytes the element kernel may plan against on device ``d``, or None.

    On a card, the smaller of what JAX has left inside its own budget and what the
    card has free, minus :data:`GPU_MEM_RESERVE`.  Both matter: the first is what the
    allocator will hand out, the second is what actually exists once hypre has taken
    its share.  On the host, where JAX declares no budget, this rank's share of the
    node's available memory (:data:`HOST_MEM_FRACTION`), so that a large element group
    is chunked rather than taken whole.
    """
    budget = None
    try:
        stats = d.memory_stats() or {}
    except Exception:                                   # noqa: BLE001
        stats = {}
    if "bytes_limit" in stats:
        budget = max(stats["bytes_limit"] - stats.get("bytes_in_use", 0), 0)
    # Only ask the GPU runtime about a GPU device: cudaMemGetInfo initializes a
    # context, and a host run must not open one (see _jaxconfig).
    on_gpu = getattr(d, "platform", "") in ("gpu", "cuda", "rocm")
    card = _gpu_free_bytes() if on_gpu else None
    if card is not None:
        budget = card if budget is None else min(budget, card)
    if budget is None:
        if on_gpu:
            return None
        return _host_free_bytes()
    return max(budget - int(GPU_MEM_RESERVE * 2 ** 30), 0)


def _is_oom(exc):
    """True for the device-out-of-memory error, whatever JAX is wrapping it in."""
    text = "%s: %s" % (type(exc).__name__, exc)
    return ("RESOURCE_EXHAUSTED" in text or "Out of memory" in text
            or "out of memory" in text)


def _release_for_retry():
    """Before a retry after the device ran out of memory: whatever else holds freed
    memory on the card gives it back (hypre's recycling pool keeps some between
    BoomerAMG setups, :func:`hippymfem.common.mfemconfig.set_hypre_pool`)."""
    try:
        from ..common.mfemconfig import hypre_pool_trim

        hypre_pool_trim()
    except Exception:                                            # noqa: BLE001
        pass


def _fits(exc, n):
    """Elements that should fit, from the size the failed allocation asked for.

    The message carries the requested byte count.  Against what the device still
    has free, that gives the factor by which the batch was too big, a far better
    starting point than halving: one retry instead of a run of failed compiles.
    Falls back to ``n // 2`` when the message cannot be read.
    """
    import re

    try:
        m = re.search(r"allocate (\d+) bytes", str(exc))
        if not m:
            return max(1, n // 2)
        want = int(m.group(1))
        free = _free_budget(device()) or 0
        if free <= 0 or want <= 0:
            return max(1, n // 2)
        # A third of what is free, not more: the failed attempt leaves the arena
        # fragmented, so ``free`` overstates what one contiguous allocation can
        # get, and the failed request is only the largest single buffer, not the
        # whole working set.
        return max(1, int(n * (0.33 * free) / want))
    except Exception:
        return max(1, n // 2)


def _analysed_per_element(raws, args, axes, probe):
    """``(need, output)``: device bytes per element of a pass, from XLA's analysis.

    ``raws`` are the jitted functions one chunk runs in turn (a Hessian pass over
    several columns runs one slot pass per column and holds every output together),
    so ``need`` is the largest scratch-plus-arguments of any of them plus the sum of
    their outputs, and ``output`` is that sum alone.  ``None`` wherever the backend or
    the program does not say, and the caller then keeps its estimate.
    """
    temps, outs = [], 0
    try:
        sub = _chunk_args(args, axes, 0, probe)
        for raw in raws:
            lower = getattr(raw, "lower", None)
            if lower is None:
                return None
            ma = lower(*sub).compile().memory_analysis()
            if ma is None:
                return None
            temps.append(int(ma.temp_size_in_bytes) + int(ma.argument_size_in_bytes))
            outs += int(ma.output_size_in_bytes)
    except Exception:                                            # noqa: BLE001
        return None
    if not temps:
        return None
    return (max(temps) + outs) / float(probe), outs / float(probe)


#: Elements per step of an element kernel on the host.  XLA runs a ``vmap`` over the
#: whole batch as one program whose intermediates have the batch's size, and on a CPU
#: core those leave the cache from about 1e4 elements on: a P1 tetrahedron's Jacobian
#: costs 0.5 us per element in a batch of 3072 and 1.8 us in one of 196608, a third
#: derivative 0.2 and 0.7 us.  On the host the batch is therefore mapped in steps of
#: this many elements *inside* the compiled program (a loop over windows of the
#: arguments), which keeps the working set in cache.  Steps of 512 elements and more
#: gave the whole-batch arrays bit for bit in every case measured; steps of a few elements
#: round differently, by an ulp, as a chunked batch does (``benchmarks/DESIGN_NOTES.md``,
#: section 1).  A GPU maps the whole batch, which is what it is fast at, and so does the
#: host when the batch fits in one step.  ``0`` maps the whole batch on the host too.  Set
#: ``HIPPYMFEM_HOST_BATCH`` or ``hm.config.host_batch``; it is read at every call, each
#: size compiling its own program.
HOST_BATCH = int(os.environ.get("HIPPYMFEM_HOST_BATCH", "2048") or 0)


def _extract_mapped(args, axes, out):
    """Append to ``out`` the subtrees of ``args`` that ``axes`` maps (``0``)."""
    if isinstance(axes, tuple):
        for x, ax in zip(args, axes):
            _extract_mapped(x, ax, out)
    elif axes is not None:
        out.append(args)


def _inject_mapped(args, axes, it):
    """``args`` with each mapped subtree replaced by the next item of ``it``."""
    if isinstance(axes, tuple):
        vals = [_inject_mapped(x, ax, it) for x, ax in zip(args, axes)]
        return list(vals) if isinstance(args, list) else tuple(vals)
    if axes is None:
        return args
    return next(it)


def _mapped_kernel(f, in_axes):
    """``jax.jit(jax.vmap(f, in_axes))``, run on the host in steps of
    :data:`HOST_BATCH` elements inside the compiled program.

    The whole-batch program and the stepped ones (one per step size) are kept apart
    and chosen at every call by the current kernel device (:func:`device`), the step
    size and the batch, so a process that moves its kernels between the host and a
    GPU (``set_device``) runs each with its own.  ``in_axes`` follows
    :func:`_chunk_args`: ``0`` maps a whole argument (every array under it), ``None``
    shares it, and a tuple recurses.
    """
    whole = jax.jit(jax.vmap(f, in_axes=in_axes))
    stepped = {}

    def stepped_fn(batch, *args):
        # Windows of ``batch`` elements read in place from the arguments, the last one
        # shifted back to end at the last element (it recomputes a few elements, with
        # the same values).  ``jax.lax.map(..., batch_size=)`` compiles the body a
        # second time for the remainder and copies the arguments to split them off.
        mapped = []
        _extract_mapped(args, in_axes, mapped)
        ne = jax.tree_util.tree_leaves(mapped)[0].shape[0]
        body = jax.vmap(lambda m: f(*_inject_mapped(args, in_axes, iter(m))))

        def window(start):
            return body(jax.tree_util.tree_map(
                lambda x: jax.lax.dynamic_slice_in_dim(x, start, batch, 0), mapped))

        shapes = jax.eval_shape(window, 0)
        out = jax.tree_util.tree_map(
            lambda sd: jnp.zeros((ne,) + sd.shape[1:], sd.dtype), shapes)

        def step(k, acc):
            start = jnp.minimum(k * batch, ne - batch)
            return jax.tree_util.tree_map(
                lambda o, r: jax.lax.dynamic_update_slice_in_dim(o, r, start, 0),
                acc, window(start))

        return jax.lax.fori_loop(0, -(-ne // batch), step, out)

    def call(*args):
        batch = HOST_BATCH
        if batch <= 0 or on_gpu():
            return whole(*args)
        mapped = []
        _extract_mapped(args, in_axes, mapped)
        leaves = jax.tree_util.tree_leaves(mapped)
        if not leaves or leaves[0].shape[0] <= batch:     # one step (or none: no elements)
            return whole(*args)
        fn = stepped.get(batch)
        if fn is None:
            fn = stepped[batch] = jax.jit(functools.partial(stepped_fn, batch))
        return fn(*args)

    # the chunk planner's XLA analysis (a GPU's) compiles the whole-batch program
    call.lower = whole.lower
    return call


def _glued_bytes(fn, args, axes, ne):
    """Bytes of ``fn``'s result over the whole batch, from its shapes at one element."""
    try:
        shapes = jax.eval_shape(fn, *_chunk_args(args, axes, 0, 1))
        one = sum(int(np.prod(s.shape)) * np.dtype(s.dtype).itemsize
                  for s in jax.tree_util.tree_leaves(shapes))
        return one * int(ne)
    except Exception:                                            # noqa: BLE001
        return None


def _chunk_args(args, axes, a, b):
    """``args`` with every element-mapped array sliced to ``[a:b]``.

    ``axes`` is the ``in_axes`` tree handed to ``vmap``: ``0`` means the element
    axis (and applies to every array under that argument, which may be a list of
    per-slot arrays), ``None`` means shared and is passed through untouched.
    """
    if isinstance(axes, tuple):
        return tuple(_chunk_args(x, ax, a, b) for x, ax in zip(args, axes))
    if axes is None:
        return args
    return jax.tree_util.tree_map(lambda z: z[a:b], args)


_SLICE = {}


def _chunk_slices(args, axes, a, b):
    """:func:`_chunk_args` for the chunk loops, in one compiled call on a GPU.

    Sliced eagerly, every element-mapped array of a chunk is an operation of its own
    (the dof arrays of each slot, the geometry, the weights: a dozen for a diffusion
    residual), each a dispatch of a few tenths of a millisecond, and a chunk cost
    1.4 to 2 ms before its kernel started.  That is what made small chunks slow and
    large ones, with the working memory they need, the faster choice.  Here one
    program cuts them all, with the start as an argument, so every chunk of one
    length reuses it.
    """
    mapped = []
    _extract_mapped(args, axes, mapped)
    leaves, treedef = jax.tree_util.tree_flatten(mapped)
    if not leaves or not on_gpu() or not all(isinstance(z, jax.Array) for z in leaves):
        return _chunk_args(args, axes, a, b)
    n = int(b - a)
    fn = _SLICE.get(n)
    if fn is None:
        fn = _SLICE[n] = jax.jit(
            lambda zs, start: [jax.lax.dynamic_slice_in_dim(z, start, n, 0) for z in zs])
    cut = treedef.unflatten(fn(leaves, a))
    return _inject_mapped(args, axes, iter(cut))


def _takes(density, n):
    """Whether ``density`` accepts ``n`` positional arguments.

    Used to decide whether a density takes the face measure.  A callable whose
    signature cannot be read (a builtin, a C function) is taken not to.
    """
    import inspect

    try:
        sig = inspect.signature(density)
    except (TypeError, ValueError):
        return False
    kinds = [p.kind for p in sig.parameters.values()]
    if any(k is inspect.Parameter.VAR_POSITIONAL for k in kinds):
        return True
    return sum(k in (inspect.Parameter.POSITIONAL_ONLY,
                     inspect.Parameter.POSITIONAL_OR_KEYWORD)
               for k in kinds) >= n


class GroupKernel:
    """Compiled element kernels for one :class:`~.elementbatch.ElementGroup`.

    Each field slot contributes its own basis tables and its own rule for turning
    element dofs into a field record at the quadrature points.  For an H1/L2 slot
    the tables are shared by every element of the group and the record is
    :class:`Field`; for an H(curl) or H(div) slot the Piola map makes them
    per-element and the record is a
    :class:`~.vectorfe.HCurlField` / :class:`~.vectorfe.HDivField`.  The two cases
    differ only in the ``in_axes`` handed to ``jax.vmap``, so nothing is broadcast
    and a scalar problem pays nothing for the vector-element support.

    A :class:`~.boundary.BoundaryGroup` is served the same way: its tables are per
    boundary element (the face-to-volume map differs from face to face), which the
    slot axes already express, and it carries the outward unit normal, which the
    density then takes after the coordinates.  Chunking, fp32 and the single
    Hessian primitive are the same for both.
    """

    def __init__(self, density, tables, group, nparams=0):
        self.density = density
        self.tables = list(tables)
        self.nslots = len(self.tables)
        self.nparams = int(nparams)
        self.group = group
        #: the per-element geometry handed to the kernels, in order; a boundary
        #: group adds the normal, and the density gets everything from ``X`` on
        geo = ("Jinv", "wdet", "X") + (
            ("nor",) if getattr(group, "nor", None) is not None else ())
        if getattr(group, "h", None) is not None:
            # The face measure is offered, not imposed: an interior facet density
            # always takes it (a penalty needs it), while a boundary density may
            # stop at the normal; the density's own signature says which.
            if getattr(group, "h_always", False) or _takes(
                    density, self.nslots + len(geo) - 1 + self.nparams):
                geo += ("h",)
        self._geo_names = geo
        self.nd = [t.nd_total for t in self.tables]
        self._cache = {}
        self._chunk = {}
        self._peak = {}
        #: ``{(device, column slot): "element" | "quadrature"}``, what ``auto`` chose
        self.hessian_route = {}
        self._slot_axes = tuple(tuple(t.jax_axes()) for t in self.tables)
        self._slot_eval = tuple(t.evaluator() for t in self.tables)
        #: Whether the ``"mixed"`` precision computes this kernel's matrices in single
        #: precision.  Off unless the owner of the kernel turns it on: single-precision
        #: matrices need the consistent Jacobian and the refined solves that go with
        #: them, which :class:`~hippymfem.modeling.PDEVariationalProblem` has for the
        #: element matrices of its domain term.  Every other kernel computes in double
        #: under ``"mixed"``.
        self.single_matrices = False
        # Tables and geometry are placed lazily and kept **per device**, so a
        # CPU-only run never touches a GPU and switching devices mid-process does
        # not leave arrays committed to the wrong one.
        self._dev = {}
        _KERNELS.append(self)

    # ----------------------------------------------------------- functional
    def _functional(self, matrix=False):
        """The element functional every derivative is built on.  ``matrix`` says that
        the derivative taken of it is an element matrix, which decides its precision
        (:func:`matrix_precision`, :func:`vector_precision`)."""
        density = self.density
        evals = self._slot_eval
        lowp = self._matrix_single() if matrix else vector_precision() == "fp32"

        def _body(dofs, tabs, geo, params):
            Jinv, wdet = geo[0], geo[1]
            fields = [ev(d, t, Jinv)
                      for d, t, ev in zip(dofs, tabs, evals)]
            # scalar parameters (time, step size, ...) are captured rather than
            # mapped, so they stay traced and changing them does not recompile;
            # the density gets the coordinates and, on a boundary, the normal
            vals = jax.vmap(lambda *a: density(*a, *params))(*fields, *geo[2:])
            return jnp.sum(wdet * vals)

        def R(dofs, tabs, geo, params):
            if not lowp:
                return _body(dofs, tabs, geo, params)
            # Cast inside the functional, so every derivative built on it inherits
            # the precision; differentiating through the cast promotes the results
            # back to float64.
            dofs, tabs, geo, params = _as32((dofs, tabs, geo, params))
            # Real fp32: XLA's default for an fp32 dot on an NVIDIA card is TF32,
            # whose 10-bit mantissa (about 5e-4 relative) through the table
            # evaluator's einsums would move the assembled operator three orders
            # past fp32 epsilon; real fp32 costs a few percent of the speedup.
            with jax.default_matmul_precision("highest"):
                return _body(dofs, tabs, geo, params)

        return R

    def _matrix_single(self):
        """Whether this kernel's element matrices are computed in single precision."""
        return PRECISION == "fp32" or (PRECISION == "mixed" and self.single_matrices)

    def _axes(self, nlead=1):
        """``in_axes`` for vmap: ``nlead`` mapped dof-like args, the tables, the
        geometry tuple (every array element-mapped), the unmapped parameters."""
        return (0,) * nlead + (self._slot_axes, 0, None)

    def _chunked(self, fn, axes, weight=1):
        """``fn``, run over the element batch in pieces the device can hold.

        The batch runs whole unless a pinned size (:data:`ELEMENT_CHUNK`) or the
        plan of :meth:`_planned` is smaller; on an out-of-memory error the chunk is
        sized down from what the allocator asked for and retried, and the size that
        worked is remembered for this device.  ``weight`` scales the planned working
        set (the full element Hessian carries every block at once and keeps its own
        remembered size).

        **Chunking changes the answer at round-off.**  XLA blocks each element's
        quadrature sum differently at different batch shapes, so a chunked result
        differs from an unchunked one by about 1e-15 relative; a given chunk size is
        reproducible, the *choice* of size is not.  That is why this is a fallback
        and not a default, and why engaging it warns.  See
        ``benchmarks/DESIGN_NOTES.md``, section 1.
        """
        def call(*args):
            ne = int(self.group.ne)
            if ne == 0:
                return fn(*args)
            d = device()
            key = (d, weight)
            n = self._chunk.get(key) or ELEMENT_CHUNK
            if not n:
                n = self._planned(fn, args, axes, d, weight, ne, glued=True)
            n = min(n, ne)
            while True:
                try:
                    if n >= ne:
                        return fn(*args)
                    parts = [fn(*_chunk_slices(args, axes, a, min(a + n, ne)))
                             for a in range(0, ne, n)]
                    return jax.tree_util.tree_map(
                        lambda *p: jnp.concatenate(p, axis=0), *parts)
                except Exception as exc:
                    if n <= 1 or not _is_oom(exc):
                        raise
                    _release_for_retry()
                    # Every chunk's output stays until they are joined, and the join
                    # copies them once more.  When that alone is more than the device
                    # has, no chunk size fits, and halving down to one element would
                    # only take minutes to say so.
                    glued = _glued_bytes(fn, args, axes, ne)
                    free = _free_budget(d)
                    if glued and free is not None and 2 * glued > free:
                        raise MemoryError(
                            "element batch of %d does not fit on %s at any chunk "
                            "size: its result is %.1f GB, held twice while the "
                            "chunks are joined, against %.1f GB free. Use more "
                            "ranks, so that each holds fewer elements."
                            % (ne, d, glued / 2 ** 30, free / 2 ** 30)) from exc
                    # At least halved, and sized from the failed request (see
                    # _fits) rather than halved blindly: every failed attempt
                    # costs a compile and XLA's rematerialization attempt.
                    n = max(1, min(n // 2, _fits(exc, n)))
                    self._chunk[key] = n
                    self._peak[key] = None
                    warnings.warn(
                        "element batch of %d did not fit on %s; retrying in "
                        "chunks of %d. Results will differ from an unchunked "
                        "run at round-off (about 1e-15 relative). Set "
                        "HIPPYMFEM_ELEMENT_CHUNK to pin a size, or use more "
                        "ranks." % (ne, d, n), RuntimeWarning, stacklevel=2)
        call._raw = fn                 # in_chunks drives the splitting itself
        call._weight = weight
        return call

    def will_chunk(self, weight=1):
        """Whether this group's batch will be split on the current device.

        Asked *before* assembling, so a caller can pick the scatter that suits:
        splitting already gives up bit-identical results against an unsplit run, so
        where it happens the fused scatter costs no further exactness and saves the
        largest allocation an assembly makes.  Where it does not happen, the glued
        path stays, and stays exact.
        """
        ne = int(self.group.ne)
        if ne == 0:
            return False
        d = device()
        n = (self._chunk.get((d, weight)) or ELEMENT_CHUNK
             or self._plan(ne, d, weight, announce=False, remember=False))
        return n < ne

    def in_chunks(self, fn, dofs, mapped, pr):
        """Run a batched kernel chunk by chunk, yielding ``(start, stop, result)``.

        The same splitting :meth:`_chunked` does, without the concatenation at the
        end.  ``fn`` is the *wrapped* kernel, so calling it on a slice would chunk
        the slice again; the unwrapped one is taken from ``_raw``.
        """
        ne = int(self.group.ne)
        if ne == 0:
            return
        args = (dofs,) + tuple(mapped) + (pr,)
        axes = self._axes()
        d = device()
        raw = getattr(fn, "_raw", fn)
        weight = getattr(fn, "_weight", 1)
        key = (d, weight)
        n = self._chunk.get(key) or ELEMENT_CHUNK
        if not n:
            n = self._planned(fn, args, axes, d, weight, ne)
        n = max(1, min(n, ne))
        a = 0
        while a < ne:
            bnd = min(a + n, ne)
            try:
                out = raw(*_chunk_slices(args, axes, a, bnd))
            except Exception as exc:
                # the streaming path had no retry: a chunk that does not fit is
                # shrunk from what the allocator asked for, as _chunked does, and the
                # same stretch is tried again
                if n <= 1 or not _is_oom(exc):
                    raise
                _release_for_retry()
                n = max(1, min(n // 2, _fits(exc, n)))
                self._chunk[key] = n
                warnings.warn(
                    "element batch of %d did not fit on %s; retrying in chunks of %d."
                    % (ne, d, n), RuntimeWarning, stacklevel=2)
                continue
            yield a, bnd, out
            a = bnd

    def _planned(self, fn, args, axes, d, weight, ne, glued=False):
        """The chunk for a pass that has no size an out-of-memory error has proven:
        the estimate, grown by XLA's analysis of the compiled pass where that says more
        fits (:data:`CHUNK_PLAN`).

        The size is remembered for this pass alone.  Keyed by the weight, as the
        estimate is, a gradient pass that fits whole would hand its answer to a Hessian
        pass of the same weight, and to :meth:`will_chunk`, which would then send an
        assembly down the glued route with a batch that must be split.  That route,
        ``glued``, keeps every chunk's output until they are joined and copies them
        once more to join them, so a split there sets twice the batch's output aside
        before sizing the chunk; the streamed route scatters each output as it comes.
        """
        pkey = (d, "plan", getattr(fn, "_raw", fn), bool(glued))
        n = self._chunk.get(pkey)
        if n is not None:
            return n
        n = self._plan(ne, d, weight, announce=False, remember=False)
        if n < ne and CHUNK_PLAN == "xla":
            raws = getattr(fn, "_slot_raws", None) or [getattr(fn, "_raw", fn)]
            probe = max(1, min(CHUNK_PROBE, n))
            need = _analysed_per_element(raws, args, axes, probe)
            free = _free_budget(d)
            if need and free:
                per_elem, out_per_elem = need
                room = CHUNK_SHARE * free
                if glued and per_elem * ne > room:
                    room -= 2 * out_per_elem * ne
                n = max(n, min(ne, int(room / per_elem)))
        self._chunk[pkey] = n
        self._announce(ne, d, n, weight)
        return n

    def _plan(self, ne, d, weight=1, announce=True, remember=True):
        """Choose a chunk size *before* trying anything, from the kernel's shape.

        Forward mode carries ``nd_total`` tangents through ``nq`` quadrature points
        at :data:`AD_DOUBLES_PER_TANGENT_QP` doubles per tangent-quadrature pair
        (measured, with margin), and a third of the free memory is the budget, which
        on the host is this rank's share of the node's (:data:`HOST_MEM_FRACTION`).  It
        is only a first guess: an under-estimate still lands in the retry of
        :meth:`_chunked`, and ``HIPPYMFEM_ELEMENT_CHUNK`` overrides the whole thing.
        Why a plan and not a probe: ``benchmarks/DESIGN_NOTES.md``, section 1.
        """
        free = _free_budget(d)
        if free is None:
            return ne                      # no budget to respect (see :func:`_free_budget`)
        nq = int(np.shape(self.group.wdet)[1]) if np.ndim(self.group.wdet) > 1 else 1
        per_elem = (AD_DOUBLES_PER_TANGENT_QP * max(sum(self.nd), 1) * max(nq, 1) * 8
                    * max(weight, 1))
        # A third of what is free, not a half: the budget is what is free when the
        # *first* chunk is planned, and XLA's peak for a chunk exceeds the largest
        # single buffer in it, so a half overshoots.
        n = int(0.33 * free / max(per_elem, 1))
        n = max(256, min(n, ne))
        if remember:
            self._chunk[(d, weight)] = n
        self._last_estimate = per_elem
        if announce:
            self._announce(ne, d, n, weight)
        return n

    def _announce(self, ne, d, n, weight=1):
        """The warning a split batch gives, with the chunk count it will run at."""
        per_elem = getattr(self, "_last_estimate", 0.0)
        if n < ne:
            # The count is reported, not warned about: a launch costs about 5 ms,
            # and at 1.9e6 P2 hexahedra on one L40S 128 chunks and 16 assembled in
            # the same time (9.3 s against 9.1).
            nchunk = -(-ne // n)
            extra = "  This is %d chunks." % nchunk
            warnings.warn(
                "element batch of %d would need about %.1f GB on %s; running in "
                "chunks of %d. Results will differ from an unchunked run at "
                "round-off (about 1e-15 relative). Set HIPPYMFEM_ELEMENT_CHUNK to "
                "pin a size, or use more ranks.%s"
                % (ne, ne * per_elem / 2 ** 30, d, n, extra),
                RuntimeWarning, stacklevel=3)
        return n

    def mapped(self, streaming=False):
        """``(tables, geometry)``: the mapped arguments, in the order the kernels
        expect.

        The per-element geometry is cached on the device unless
        :meth:`_stream_geometry` finds the batch split and the geometry too large a
        share of the budget; it is then left on the host, and a chunk loop slices it,
        so that only a chunk's rows are transferred instead of the whole
        ``(ne, nq, dim, sdim)`` staying resident (gigabytes on a large mesh, against
        megabytes per chunk).  ``streaming`` is the request of a chunk loop.  It used
        to get the host arrays whatever was cached, which transferred the whole
        geometry, chunk by chunk, at every assembly of a split batch although the
        device held a copy for the other kernels: 1.7 GB for 262 144 second-order
        hexahedra, more than half of what such an assembly took outside its kernel.
        Now the device copy serves the chunk loop too.  Tables are per group and stay
        on the device either way.
        """
        d = device()
        ent = self._dev.get(d)
        if ent is None:
            # one device copy per group and per space table, whichever kernel asks
            tabs = tuple(tuple(_shared_put(t, ("tables", k), a)
                               for k, a in enumerate(t.jax_tables()))
                         for t in self.tables)
            geo = None if self._stream_geometry(d) else tuple(
                _shared_put(self.group, n, getattr(self.group, n))
                for n in self._geo_names)
            ent = self._dev[d] = (tabs, geo)
        tabs, geo = ent
        if geo is None:
            geo = tuple(getattr(self.group, n) for n in self._geo_names)
        return (tabs, geo)

    def _stream_geometry(self, d):
        """Whether to leave this group's geometry on the host for every caller.

        The size test comes first, so a geometry under
        :data:`GEOMETRY_STREAM_FRACTION` of the budget is cached on the device
        without planning the batch.  Only above it is the batch planned, and a batch
        that is not split still gets the device copy, since an unsplit kernel would
        upload the whole geometry per call anyway.
        """
        if GEOMETRY_STREAM_FRACTION <= 0 or int(self.group.ne) == 0:
            return False
        try:
            stats = d.memory_stats()
        except Exception:
            stats = None
        if not stats or "bytes_limit" not in stats:
            return False                   # a host device has no budget to respect
        g = self.group
        nbytes = sum(getattr(g, n).nbytes for n in self._geo_names)
        if nbytes <= GEOMETRY_STREAM_FRACTION * stats["bytes_limit"]:
            return False
        return self.will_chunk()

    # ---------------------------------------------------------------- blocks
    def grad_block(self, i):
        """Batched ``dR/d(dofs_i)``; returns ``(ne, nd_i)``."""
        key = ("g", i)
        if key not in self._cache:
            R = self._functional()

            def f(dofs, tabs, geo, params):
                return jax.grad(lambda z: R(z, tabs, geo, params))(dofs)[i]

            self._cache[key] = self._chunked(
                _mapped_kernel(f, self._axes()), self._axes())
        return self._cache[key]

    def _hess_slot(self, j):
        """Every row block of the Hessian with forward tangents over slot ``j`` only.

        Returns a callable giving a tuple over row slots ``i`` of ``(ne, nd_i, nd_j)``.
        This is the one differentiation primitive behind :meth:`hess_block`,
        :meth:`hess_cols` and :meth:`hess_all`, so that all three return the same
        bits: XLA rounds a forward pass differently for a different number of
        tangents (``benchmarks/DESIGN_NOTES.md``, section 1).  Per slot the program
        is the same whoever asks, and selecting rows happens outside the compiled
        function; a pass pushes ``nd_j`` tangents, only the columns asked for.  Which
        program that is, the element route or the quadrature one, is
        :data:`HESSIAN_MODE`'s choice.
        """
        key = ("hs", int(j))
        if key not in self._cache:
            mode = HESSIAN_MODE
            if mode == "element" or not self._quadrature_route():
                self._cache[key] = self._hess_slot_element(j)
            elif mode == "quadrature":
                self._cache[key] = self._hess_slot_quadrature(j)
            else:
                self._cache[key] = self._fastest(
                    j, self._hess_slot_element(j), self._hess_slot_quadrature(j))
        return self._cache[key]

    def _slot_weight(self, j):
        # the planner's working set is per tangent, so a slot pass plans at its share
        # of the tangents
        return max(1.0, self.nslots * self.nd[j] / max(sum(self.nd), 1))

    def _hess_slot_element(self, j):
        """:meth:`_hess_slot` by forward tangents over slot ``j``'s element dofs."""
        return self._chunked(_mapped_kernel(self._hess_slot_element_fn(j), self._axes()),
                             self._axes(), weight=self._slot_weight(j))

    def _hess_slot_element_fn(self, j):
        """The function of one element behind :meth:`_hess_slot_element`."""
        R = self._functional(matrix=True)
        nslots = self.nslots
        lowp = self._matrix_single()

        def f(dofs, tabs, geo, params):
            def g(zj):
                z = tuple(zj if s == j else dofs[s] for s in range(nslots))
                return jax.grad(lambda zz: R(zz, tabs, geo, params))(z)
            out = jax.jacfwd(g)(dofs[j])
            return _symmetric_diagonal(out, j) if lowp else out

        return f

    def _quadrature_route(self):
        """Whether every slot evaluates its field from shared or per-element tables
        ``(N, G)`` (H1 and L2 on elements and on the boundary); a Piola map or two
        sides take the element route."""
        return all(type(t).__name__ in ("SpaceTables", "BoundarySpaceTables")
                   for t in self.tables)

    def _hess_slot_quadrature(self, j):
        """:meth:`_hess_slot` from second derivatives of the density at the points.

        At each point the density is differentiated with respect to every slot's values
        and physical gradients, forward over slot ``j``'s, which gives the pointwise
        blocks ``D[s][r][c]``: row slot ``s``, its values or gradients ``r``, slot
        ``j``'s values or gradients ``c``.  The fields are linear in the dofs, so the
        element block is ``sum_q w_q Psi_r^T D Psi_c`` with ``Psi`` the basis values or
        physical gradients, component by component.  The blocks that are identically
        zero are found once from the density's trace (:meth:`_zero_point_blocks`) and
        skipped, as the element route's forward tangents skip them: a residual linear
        in the state has no state-state block, and most densities couple few of the
        parts.  Equal to the element route to round-off.
        """
        return self._chunked(_mapped_kernel(self._hess_slot_quadrature_fn(j), self._axes()),
                             self._axes(), weight=self._slot_weight(j))

    def _hess_slot_quadrature_fn(self, j):
        """The function of one element behind :meth:`_hess_slot_quadrature`."""
        evals = self._slot_eval
        nslots = self.nslots
        vd = [int(t.vdim) for t in self.tables]
        nd = [int(t.nd) for t in self.tables]
        sdim = int(np.shape(self.group.Jinv)[-1])
        lowp = self._matrix_single()
        zero = self._zero_point_blocks(j)

        def body(dofs, tabs, geo, params):
            Jinv, wdet = geo[0], geo[1]
            fields = [ev(d, t, Jinv) for ev, d, t in zip(evals, dofs, tabs)]

            def at_point(fq, *extra):
                return self._point_blocks(j, tuple((f.val, f.grad) for f in fq), extra,
                                          params)

            D = jax.vmap(at_point)(fields, *geo[2:])
            nq = wdet.shape[0]

            def basis(t):
                N, G = t
                return (N[:, None, :], jnp.einsum("qil,qlk->qki", G, Jinv))

            Pj = basis(tabs[j])
            F = (1, sdim)
            out = []
            for s in range(nslots):
                Ps = basis(tabs[s])
                E = None
                for r in range(2):
                    for c in range(2):
                        if (s, r, c) in zero:
                            continue
                        blk = jnp.reshape(D[s][r][c], (nq, vd[s], F[r], vd[j], F[c]))
                        T = jnp.einsum("qafbg,qgl->qafbl",
                                       blk * wdet[:, None, None, None, None], Pj[c])
                        e = jnp.einsum("qfk,qafbl->akbl", Ps[r], T)
                        E = e if E is None else E + e
                shape = (vd[s] * nd[s], vd[j] * nd[j])
                out.append(jnp.zeros(shape, wdet.dtype) if E is None else E.reshape(shape))
            return tuple(out)

        def f(dofs, tabs, geo, params):
            if not lowp:
                return body(dofs, tabs, geo, params)
            args = _as32((dofs, tabs, geo, params))
            with jax.default_matmul_precision("highest"):
                return _symmetric_diagonal(
                    tuple(o.astype(jnp.float64) for o in body(*args)), j)

        return f

    # ------------------------------------------------- single precision, consistent
    def _low_modes(self, j):
        """The constants of slot ``j`` as element dof vectors, orthonormal rows of a
        ``(k, nd_j)`` array: one per component of a nodal space, where a vector of ones
        is the constant function.  Any other space gets the vector of ones, which is a
        test vector like any other."""
        t = self.tables[j]
        n = int(t.nd_total)
        if type(t).__name__ in ("SpaceTables", "BoundarySpaceTables"):
            vd, nd = int(t.vdim), int(t.nd)
            V = np.zeros((vd, n))
            for c in range(vd):
                V[c, c * nd:(c + 1) * nd] = 1.0 / np.sqrt(nd)
            return V
        return np.full((1, n), 1.0 / np.sqrt(n))

    def consistent_block(self, i, j, symmetric=False):
        """Block ``(i, j)`` in single precision, exact on the constants.

        An element matrix computed in single precision is off by about 1e-7 of its
        entries, and on a mesh of like elements every element makes the *same* error.
        The assembled matrix then errs coherently: applied to a smooth function, whose
        values on an element are nearly equal, the errors of a row add up to the defect
        of its row sum, the same on every element, where the exact entries cancel.  A
        solve amplifies that by the condition number.  Measured on the Jacobian of the
        model problem at ``16^3`` second-order hexahedra, with a constant coefficient:
        an incremental solve was off by 2.2e-4, and by 2.7e-7 with the row sums put
        right.

        So the block is computed in single precision and corrected by a matrix of rank
        one per component: its product with the constants of slot ``j``, and that of
        its transpose with the constants of slot ``i``, are replaced by the
        double-precision ones, which are two derivative passes with one tangent each
        (a matrix pass has one per element dof).  ``symmetric`` says that the block is
        a symmetric matrix: it is then symmetrized first, one pass serves both sides,
        and the result is symmetric to the last bit.
        """
        key = ("hc", int(i), int(j), bool(symmetric))
        if key not in self._cache:
            route = HESSIAN_MODE
            if route == "auto":
                route = self.hessian_route.get((device(), int(j)), "element")
            slot = (self._hess_slot_quadrature_fn(j)
                    if route == "quadrature" and self._quadrature_route()
                    else self._hess_slot_element_fn(j))
            R = self._functional()               # the vectors' precision: double
            nslots = self.nslots
            Vj = jnp.asarray(self._low_modes(j))
            Vi = Vj if symmetric else jnp.asarray(self._low_modes(i))

            def f(dofs, tabs, geo, params):
                K = slot(dofs, tabs, geo, params)[i]

                def action(row, col, v):
                    # d2R / d(dofs_row) d(dofs_col) applied to v, one forward tangent
                    def g(z):
                        zz = tuple(z if s == col else dofs[s] for s in range(nslots))
                        return jax.grad(lambda w: R(w, tabs, geo, params))(zz)[row]
                    return jax.jvp(g, (dofs[col],), (v,))[1]

                Rj = jax.vmap(lambda v: action(i, j, v), out_axes=1)(Vj)       # (nd_i, kj)
                if symmetric:
                    # every term symmetric bit for bit, and so is their sum
                    K = 0.5 * (K + K.T)
                    Dj = Rj - K @ Vj.T
                    U = Dj @ Vj
                    S = Vj @ Dj
                    W = Vj.T @ (0.5 * (S + S.T)) @ Vj
                    return K + (U + U.T) - 0.5 * (W + W.T)
                Ri = jax.vmap(lambda v: action(j, i, v), out_axes=1)(Vi)       # (nd_j, ki)
                Dj = Rj - K @ Vj.T
                Di = Ri - K.T @ Vi.T
                return K + Dj @ Vj + Vi.T @ Di.T - Vi.T @ (Vi @ Dj) @ Vj

            self._cache[key] = self._chunked(
                _mapped_kernel(f, self._axes()), self._axes(), weight=self._slot_weight(j))
        return self._cache[key]

    def _block_fn(self, i, j, consistent=None):
        """:meth:`hess_block`, or :meth:`consistent_block` where ``consistent`` asks
        for it (``"symmetric"`` or ``"two-sided"``) and the matrices of this kernel are
        in single precision while its vectors are not."""
        if consistent and self._matrix_single() and vector_precision() == "fp64":
            return self.consistent_block(i, j, symmetric=(consistent == "symmetric"))
        return self.hess_block(i, j)

    def _point_blocks(self, j, parts, extra, params, split=False):
        """The density's second derivatives at one point, ``D[s][r][c]``, forward over
        slot ``j``'s values and gradients (see :meth:`_hess_slot_quadrature`).

        ``parts`` holds every slot's ``(value, gradient)`` at the point.  One forward
        pass over both of slot ``j``'s parts is the faster program; ``split`` makes one
        pass per part, so that a part no row depends on gives a block of its own that
        the trace shows to be constant (:meth:`_zero_point_blocks`).
        """
        density = self.density
        nslots = self.nslots

        def dens(ps):
            return density(*[Field(v, g) for (v, g) in ps], *extra, *params)

        def grad_all(vj, gj):
            return jax.grad(dens)(tuple((vj, gj) if s == j else parts[s]
                                        for s in range(nslots)))

        if not split:
            return jax.jacfwd(lambda pj: grad_all(*pj))(parts[j])
        dv = jax.jacfwd(grad_all, argnums=0)(*parts[j])
        dg = jax.jacfwd(grad_all, argnums=1)(*parts[j])
        return tuple(tuple((dv[s][r], dg[s][r]) for r in range(2)) for s in range(nslots))

    def _zero_point_blocks(self, j):
        """The ``(s, r, c)`` of the pointwise blocks that are identically zero.

        A block is taken to be zero when the traced program computes it from none of
        its inputs (the fields, the coordinates and the parameters) and its value is
        zero, which holds at every point, whatever branches the density takes.  A trace
        that cannot be read keeps every block.
        """
        from jax.extend import core as jcore

        vd = [int(t.vdim) for t in self.tables]
        sdim = int(np.shape(self.group.Jinv)[-1])
        rng = np.random.default_rng(0)

        def part(v):
            shape = () if v == 1 else (v,)
            return (jnp.asarray(rng.uniform(0.1, 0.5, shape)),
                    jnp.asarray(rng.uniform(-0.5, 0.5, shape + (sdim,))))

        parts = tuple(part(v) for v in vd)
        extra = tuple(jnp.asarray(rng.uniform(0.1, 0.9, np.shape(getattr(self.group, n))[2:]))
                      for n in self._geo_names[2:])
        params = tuple(jnp.asarray(1.0) for _ in range(self.nparams))

        def leaves(p, e, q):
            return jax.tree_util.tree_leaves(self._point_blocks(j, p, e, q, split=True))

        try:
            jaxpr = jax.make_jaxpr(leaves)(parts, extra, params).jaxpr
            dep = set(jaxpr.invars)
            for eqn in jaxpr.eqns:
                if any(not isinstance(v, jcore.Literal) and v in dep for v in eqn.invars):
                    dep.update(eqn.outvars)
            vals = leaves(parts, extra, params)
        except Exception:                                        # noqa: BLE001
            return frozenset()
        keys = [(s, r, c) for s in range(self.nslots) for r in range(2) for c in range(2)]
        return frozenset(
            key for key, v, val in zip(keys, jaxpr.outvars, vals)
            if (isinstance(v, jcore.Literal) or v not in dep)
            and not np.any(np.asarray(val)))

    def _route_key(self, j):
        """The program a slot pass of this kernel compiles, as :data:`_ROUTES` keys it."""
        wdet = self.group.wdet
        nq = int(np.shape(wdet)[1]) if np.ndim(wdet) > 1 else 1
        return (id(self.density),
                tuple((type(t).__name__, int(t.nd), int(t.vdim)) for t in self.tables),
                int(self.group.ne), nq, int(self.nparams), PRECISION, int(j))

    def _fastest(self, j, a, b):
        """``a`` or ``b`` (the element and the quadrature route of a slot), whichever
        runs faster, timed on the device at the first call of any kernel with this
        program (both compiled and run twice there) and kept in :data:`_ROUTES`; what
        this kernel took is in :attr:`hessian_route`.  One route's output is held at a
        time, so the timing needs no more memory than a pass."""
        names = ("element", "quadrature")
        key = self._route_key(j)

        def pick(fa, fb, args):
            d = device()
            k = _ROUTES.get(key + (d,))
            if k is not None:
                self.hessian_route[(d, int(j))] = names[k]
                return k, (fa, fb)[k](*args)
            best, out = None, None
            for k, fn in enumerate((fa, fb)):
                out = None
                jax.block_until_ready(fn(*args))                  # compile
                t0 = time.perf_counter()
                out = fn(*args)
                jax.block_until_ready(out)
                t = time.perf_counter() - t0
                if best is None or t < best[0]:
                    best = (t, k)
            k = _ROUTES[key + (d,)] = best[1]
            self.hessian_route[(d, int(j))] = names[k]
            if k != 1:
                out = None
                out = fa(*args)
            return k, out

        def call(*args):
            return pick(a, b, args)[1]

        def raw(*args):
            return pick(a._raw, b._raw, args)[1]

        # the chunk planner's XLA analysis sizes the chunk by the element route's program
        raw.lower = getattr(a._raw, "lower", None)
        call._raw = raw
        call._weight = a._weight
        return call

    def hess_block(self, i, j):
        """Batched ``d2R/d(dofs_i) d(dofs_j)``; returns ``(ne, nd_i, nd_j)``.

        Row index is ``i`` (the test space), column index is ``j`` (the trial
        space), which is MFEM's ``elmat`` convention.  Rows ``i`` of the slot pass
        :meth:`_hess_slot` ``(j)``, selected after the compiled function.
        """
        key = ("h", i, j)
        if key not in self._cache:
            slot = self._hess_slot(j)

            def call(*args):
                return slot(*args)[i]
            call._raw = lambda *args: slot._raw(*args)[i]
            call._slot_raws = [slot._raw]
            call._weight = slot._weight
            self._cache[key] = call
        return self._cache[key]

    def hess_cols(self, cols):
        """The Hessian blocks whose *column* slot is in ``cols``: ``H[i][k]`` of
        shape ``(ne, nd_i, nd_cols[k])`` for every row slot ``i``.

        A Newton linearization point never asks for the adjoint columns (its
        blocks are ``C``, ``W_uu``, ``W_um``, ``W_mm``: columns ``u`` and ``m``), and
        a residual linear in the state needs the ``m`` columns alone.  One slot pass
        per column (:meth:`_hess_slot`) does that much work and no more, holds
        ``(ne, nd, nd_j)`` arrays instead of ``(ne, nd, nd)``, so a batch splits into
        fewer chunks, and is bit-identical to :meth:`hess_block` by construction.
        """
        cols = tuple(int(c) for c in cols)
        key = ("hcols", cols)
        if key not in self._cache:
            slots = [self._hess_slot(c) for c in cols]
            nslots = self.nslots

            def stack(parts):
                return tuple(tuple(parts[k][i] for k in range(len(cols)))
                             for i in range(nslots))

            def call(*args):
                return stack([sl(*args) for sl in slots])
            call._raw = lambda *args: stack([sl._raw(*args) for sl in slots])
            call._slot_raws = [sl._raw for sl in slots]
            call._weight = max(1.0, self.nslots * sum(self.nd[c] for c in cols)
                               / max(sum(self.nd), 1))
            self._cache[key] = call
        return self._cache[key]

    def hess_all(self):
        """Every Hessian block at once: ``H[i][j]`` of shape ``(ne, nd_i, nd_j)``,
        :meth:`hess_cols` over every slot."""
        return self.hess_cols(range(self.nslots))

    def hvp_block(self, i, j):
        """Batched ``d2R/d_i d_j`` applied to a direction in slot ``j``.

        Returns a callable ``(dofs, jdir, tabs, geo, params) -> (ne, nd_i)``: one
        forward tangent through the slot-``i`` gradient, where the assembled block
        takes ``nd_j`` tangents and a scatter into a matrix.  For a block applied once
        or twice at a point (the sample loop of a sample-average Hessian) this is the
        cheaper way to its products.
        """
        key = ("hv", i, j)
        if key not in self._cache:
            R = self._functional()
            nslots = self.nslots

            def f(dofs, jdir, tabs, geo, params):
                # differentiated in slot j alone: zero tangents in the other slots would
                # be carried through the whole element, where JAX drops a slot that has
                # none (a product into the state row costs 10x more with them)
                def gi(zj):
                    zz = tuple(zj if s == j else dofs[s] for s in range(nslots))
                    return jax.grad(lambda w: R(w, tabs, geo, params))(zz)[i]

                return jax.jvp(gi, (dofs[j],), (jdir,))[1]

            self._cache[key] = self._chunked(
                _mapped_kernel(f, self._axes(2)), self._axes(2))
        return self._cache[key]

    def third_block(self, i, j, k):
        """Batched ``d3R/d_i d_j d_k`` contracted with directions in slots ``j``, ``k``.

        Returns a callable ``(dofs, jdir, kdir, tabs, geo, params) -> (ne, nd_i)``,
        where ``jdir`` and ``kdir`` are element dof arrays for arguments ``j`` and
        ``k``.
        """
        key = ("t", i, j, k)
        if key not in self._cache:
            R = self._functional()
            nslots = self.nslots

            def f(dofs, jdir, kdir, tabs, geo, params):
                # differentiated in slots j and k alone (see hvp_block)
                def put(zz, slot, v):
                    return tuple(v if s == slot else zz[s] for s in range(nslots))

                def gi(zz):
                    return jax.grad(lambda w: R(w, tabs, geo, params))(zz)[i]

                def dk(zj):
                    base = put(dofs, j, zj)
                    return jax.jvp(lambda zk: gi(put(base, k, zk)), (base[k],), (kdir,))[1]

                return jax.jvp(dk, (dofs[j],), (jdir,))[1]

            self._cache[key] = self._chunked(
                _mapped_kernel(f, self._axes(3)), self._axes(3))
        return self._cache[key]

    def third_dir_block(self, i, nmodes, present=None):
        r"""Batched :math:`\sum_m w_m\, D^2(\partial_i R)[t_m, t_m]`: the second
        directional derivative of the slot-``i`` gradient along directions ``t_m`` that
        may span every slot, weighted and summed over ``nmodes`` directions.

        Returns a callable ``(dofs, T, w, tabs, geo, params) -> (ne, nd_i)``, where ``T``
        is a tuple over the slots of element dof arrays ``(ne, nmodes, nd_s)`` and ``w``
        the ``nmodes`` weights.  With ``t = (t_j, t_k)`` over two slots it is
        :meth:`third_block` summed over both orders and both diagonals,
        :math:`R_{ijj}[t_j, t_j] + 2 R_{ijk}[t_j, t_k] + R_{ikk}[t_k, t_k]`, in one pass
        instead of four; the directions share the gather of the point and the scatter.
        ``present`` names the slots the directions have components in (every slot by
        default), and ``T`` then holds those slots' arrays alone: the others are not
        differentiated at all (see :meth:`hvp_block`).
        """
        present = (tuple(range(self.nslots)) if present is None
                   else tuple(sorted(int(s) for s in present)))
        key = ("td", i, int(nmodes), present)
        if key not in self._cache:
            R = self._functional()

            def f(dofs, T, w, tabs, geo, params):
                def at(zp):
                    zz = list(dofs)
                    for s, v in zip(present, zp):
                        zz[s] = v
                    return tuple(zz)

                def gi(zp):
                    return jax.grad(lambda z: R(z, tabs, geo, params))(at(zp))[i]

                base = tuple(dofs[s] for s in present)

                def dd(t):
                    def dk(zp):
                        return jax.jvp(gi, (zp,), (t,))[1]
                    return jax.jvp(dk, (base,), (t,))[1]

                return jnp.tensordot(w, jax.vmap(dd)(T), axes=1)

            axes = (0, 0, None) + self._axes()[1:]
            self._cache[key] = self._chunked(_mapped_kernel(f, axes), axes,
                                             weight=max(1.0, float(nmodes)))
        return self._cache[key]

    def residual_value(self):
        """Batched ``R`` itself (one scalar per element); used for form integrals."""
        key = ("v",)
        if key not in self._cache:
            R = self._functional()

            self._cache[key] = self._chunked(_mapped_kernel(R, self._axes()), self._axes())
        return self._cache[key]

    # -------------------------------------------------------------- dispatch
    def geometry(self):
        """Deprecated alias for the geometry arrays alone; prefer :meth:`mapped`."""
        return self.mapped()[1]

    def gather(self, local_arrays):
        """Element dof arrays for this group from local (ghosted) dof vectors.

        The indexing runs **where the kernels run**: the local dof vector (one
        value per local dof) is copied to the device and gathered there, rather
        than gathered on the host and copied element by element.  For a P1
        quadrilateral space that is a quarter of the transfer, and it keeps the
        element dof array off the host entirely.
        """
        if len(local_arrays) != self.nslots:
            raise ValueError("expected %d field arrays, got %d"
                             % (self.nslots, len(local_arrays)))
        return tuple(t.gather_device(a) for t, a in zip(self.tables, local_arrays))


def _symmetric_diagonal(blocks, j):
    """The row blocks of a slot pass over column slot ``j`` with the ``(j, j)`` block
    symmetrized.  That block is a second derivative of a scalar and symmetric; in
    double precision AD returns it so to the last bits, in single precision to about
    1e-7, and a Hessian that is not symmetric to rounding costs CG its short
    recurrence (measured: the full-Newton steps of the model problem took 30 to 40%
    more CG iterations)."""
    out = list(blocks)
    out[j] = 0.5 * (out[j] + out[j].T)
    return tuple(out)


def _result(arr):
    """A kernel result, left on the device when that is where it was computed.

    Copying it to the host here would undo the point of running on a GPU: the
    scatter into the CSR structure can consume it in place and return only the
    assembled values.  On the CPU backend a numpy view is returned.
    """
    if device().platform == "cpu":
        return np.asarray(arr)
    return arr


def _params(params):
    """Scalar parameters as a tuple of device arrays (traced, not baked in)."""
    return tuple(jax.device_put(np.asarray(v, dtype=np.float64), device()) for v in params)


class QuadratureKernel:
    """Element kernels for a residual density over a whole (possibly mixed) mesh.

    Parameters
    ----------
    density : callable
        ``density(u, m, p, x, *aux, *params) -> scalar``, JAX-traceable, with
        :class:`Field` arguments for the fields.
    spaces : sequence of FunctionSpace
        One per field slot, in the order the density expects them.  The
        stationary problem uses three, ``[STATE, PARAMETER, ADJOINT]``; a
        one-step time-dependent problem uses four, with the previous time level
        in slot 1, so that the adjoint's time coupling is an exact derivative
        rather than a difference.
    batches : MeshBatches
    nparams : int
        Number of trailing scalar arguments (time, step size, ...).  They are
        passed as traced values, so changing them between calls reuses the
        compiled kernel instead of triggering a recompile.
    """

    def __init__(self, density, spaces, batches, nparams=0):
        self.density = density
        self.spaces = list(spaces)
        self.nslots = len(self.spaces)
        self.nparams = int(nparams)
        self.batches = batches
        device()          # resolved here, where every rank arrives (see _node_rank)
        tabs = [batches.tables(sp) for sp in self.spaces]
        self.group_kernels = [
            GroupKernel(
                density,
                [tabs[k][gi] for k in range(self.nslots)],
                batches.groups[gi],
                nparams=self.nparams,
            )
            for gi in range(len(batches.groups))
        ]

    @property
    def groups(self):
        return self.batches.groups

    def tables(self, gi):
        return self.group_kernels[gi].tables

    # -------------------------------------------------------------- evaluate
    def element_matrices(self, i, j, local_arrays, params=(), consistent=None):
        """Element matrices of block ``(i, j)``, one array per element group.

        ``consistent`` (``"symmetric"`` or ``"two-sided"``) asks, where the matrices
        are computed in single precision, for the ones that are exact on the constants
        (:meth:`GroupKernel.consistent_block`): for a matrix that will be inverted.
        """
        out = []
        pr = _params(params)
        for gk in self.group_kernels:
            dofs = gk.gather(local_arrays)
            out.append(gk.tables[i].transform_dual_matrix(
                _result(gk._block_fn(i, j, consistent)(dofs, *gk.mapped(), pr)),
                gk.tables[j]))
        return out

    def will_chunk(self, weight=1):
        return any(gk.will_chunk(weight) for gk in self.group_kernels)

    def element_matrices_or_chunks(self, i, j, local_arrays, params=(), consistent=None):
        """The arrays when the batch fits whole, a chunk thunk when it does not.

        Bit-identical to :meth:`element_matrices` in the first case, and in the
        second the splitting has already cost that, so the fused scatter is free.
        """
        if self.will_chunk():
            return lambda: self.element_matrix_chunks(i, j, local_arrays, params,
                                                      consistent=consistent)
        return self.element_matrices(i, j, local_arrays, params, consistent=consistent)

    def element_matrix_chunks(self, i, j, local_arrays, params=(), consistent=None):
        """Yield ``(group, start, stop, array)`` for block ``(i, j)``.

        The same work :meth:`element_matrices` does, handed over a chunk at a time
        instead of glued into one ``(ne, nd, nd)`` array per group, the largest
        resident allocation an assembly would make; the scatter consumes each chunk
        (:meth:`~hippymfem.fem.csrassemble.ScatterPattern.data_fused`).
        """
        pr = _params(params)
        for g, gk in enumerate(self.group_kernels):
            dofs = gk.gather(local_arrays)
            fn = gk._block_fn(i, j, consistent)
            # streaming geometry: this path only runs when the batch is split, and
            # that is exactly when keeping all of it resident is what hurts
            for a, bnd, out in gk.in_chunks(fn, dofs, gk.mapped(streaming=True), pr):
                yield g, a, bnd, gk.tables[i].transform_dual_matrix(
                    _result(out), gk.tables[j])

    def element_matrix_chunks_many(self, pairs, local_arrays, params=()):
        """Yield ``(group, start, stop, {(i, j): array})`` from one differentiation.

        :meth:`element_matrices_many` glues every block's full ``(ne, nd, nd)``
        array on the device and concatenates the chunk parts to get there; that glue,
        resident plus a transient copy, is a device peak no chunk size changes.  This
        yields the same blocks a chunk at a time, from the same single pass, so the
        scatter can consume each chunk and nothing larger than a chunk is ever
        resident.
        """
        pairs = [tuple(p) for p in pairs]
        cols = tuple(sorted({j for (_, j) in pairs}))
        pr = _params(params)
        for g, gk in enumerate(self.group_kernels):
            dofs = gk.gather(local_arrays)
            fn = gk.hess_cols(cols)
            for a, bnd, H in gk.in_chunks(fn, dofs, gk.mapped(streaming=True), pr):
                yield g, a, bnd, {
                    (i, j): gk.tables[i].transform_dual_matrix(
                        _result(H[i][cols.index(j)]), gk.tables[j])
                    for (i, j) in pairs}

    def element_matrices_many(self, pairs, local_arrays, params=()):
        """Several blocks from one differentiation pass.

        ``pairs`` is a sequence of ``(i, j)``.  Wherever a linearization point
        needs more than one block, which is every Newton step, this is the
        cheaper way to get them: one differentiation pass over the column slots
        the pairs use (:meth:`GroupKernel.hess_cols`) instead of one pass per
        block.  Returns ``{(i, j): [array per group]}``, holding exactly the
        arrays :meth:`element_matrices` returns for each pair.
        """
        pairs = [tuple(p) for p in pairs]
        cols = tuple(sorted({j for (_, j) in pairs}))
        out = {ij: [] for ij in pairs}
        pr = _params(params)
        for gk in self.group_kernels:
            dofs = gk.gather(local_arrays)
            H = gk.hess_cols(cols)(dofs, *gk.mapped(), pr)
            for (i, j) in pairs:
                out[(i, j)].append(gk.tables[i].transform_dual_matrix(
                    _result(H[i][cols.index(j)]), gk.tables[j]))
        return out

    def element_vectors(self, i, local_arrays, params=()):
        """Element residual vectors of block ``i``, one array per element group."""
        out = []
        pr = _params(params)
        for gk in self.group_kernels:
            dofs = gk.gather(local_arrays)
            out.append(gk.tables[i].transform_dual_vector(
                _result(gk.grad_block(i)(dofs, *gk.mapped(), pr))))
        return out

    def element_hvp(self, i, j, local_arrays, jdir_local, params=()):
        """Element vectors of the second-derivative block ``(i, j)`` applied to a
        direction in slot ``j``, without forming the block (:meth:`GroupKernel.hvp_block`)."""
        out = []
        pr = _params(params)
        for gk in self.group_kernels:
            dofs = gk.gather(local_arrays)
            jd = _put(gk.tables[j].gather(jdir_local))
            out.append(gk.tables[i].transform_dual_vector(_result(
                gk.hvp_block(i, j)(dofs, jd, *gk.mapped(), pr))))
        return out

    def element_third(self, i, j, k, local_arrays, jdir_local, kdir_local,
                      params=()):
        """Element vectors of the third-derivative block contracted with two directions."""
        out = []
        pr = _params(params)
        for gk in self.group_kernels:
            dofs = gk.gather(local_arrays)
            jd = _put(gk.tables[j].gather(jdir_local))
            kd = _put(gk.tables[k].gather(kdir_local))
            out.append(gk.tables[i].transform_dual_vector(_result(
                gk.third_block(i, j, k)(dofs, jd, kd, *gk.mapped(), pr))))
        return out

    def element_third_dir(self, i, local_arrays, dir_locals, weights, params=()):
        r"""Element vectors of :math:`\sum_m w_m\, D^2(\partial_i R)[t_m, t_m]` (see
        :meth:`GroupKernel.third_dir_block`).

        ``dir_locals`` holds one direction per weight, each a sequence over the slots of
        local dof arrays, ``None`` where the direction has no component.
        """
        out = []
        pr = _params(params)
        m = len(dir_locals)
        w = _put(np.asarray(weights, dtype=np.float64).reshape(m))
        present = tuple(s for s in range(len(dir_locals[0]))
                        if any(d[s] is not None for d in dir_locals))
        for gk in self.group_kernels:
            dofs = gk.gather(local_arrays)
            T = []
            for s in present:
                cols = [jnp.zeros_like(dofs[s]) if d[s] is None
                        else gk.tables[s].gather_device(d[s]) for d in dir_locals]
                T.append(jnp.stack(cols, axis=1))
            out.append(gk.tables[i].transform_dual_vector(_result(
                gk.third_dir_block(i, m, present)(dofs, tuple(T), w, *gk.mapped(), pr))))
        return out

    def element_values(self, local_arrays, params=()):
        """Per-element integrals of the density (used for functional evaluation)."""
        out = []
        pr = _params(params)
        for gk in self.group_kernels:
            dofs = gk.gather(local_arrays)
            out.append(np.asarray(gk.residual_value()(dofs, *gk.mapped(), pr)))
        return out


class BoundaryKernel(QuadratureKernel):
    """AD kernels for a boundary density: :class:`QuadratureKernel` over
    :class:`~.boundary.BoundaryBatches`.

    ``density(u, m, p, x, n, *params) -> scalar`` with the same :class:`Field`
    records as the domain density, plus the outward unit normal ``n``, which the
    boundary groups carry and the group kernel hands to the density after the
    coordinates.  Everything else is the domain kernel's.
    """
