# Copyright (c) 2026, Peng Chen, Georgia Institute of Technology.
# This file is part of hIPPyMFEM, free software under the GNU General Public
# License version 2.0 dated June 1991 (GPL-2.0-only); see the files LICENSE and
# COPYRIGHT.
"""hIPPyMFEM: deterministic and Bayesian inverse problems on MFEM.

The user supplies a pointwise residual density for the forward PDE; every operator
the inverse problem needs (the adjoint, the parameter Jacobian, the second-order blocks
of the Lagrangian) is generated by automatic differentiation at the quadrature points
and assembled in parallel into hypre matrices, on the host or on GPUs.

Quick start::

    import mfem.par as mfem, jax.numpy as jnp
    from mpi4py import MPI
    import hippymfem as hm

    mfem.Hypre.Init()
    mesh = mfem.ParMesh(MPI.COMM_WORLD,
                        mfem.Mesh.MakeCartesian2D(32, 32, mfem.Element.TRIANGLE))
    Vu = hm.FunctionSpace.H1(mesh, 2)
    Vm = hm.FunctionSpace.H1(mesh, 1)

    def pde_varf(u, m, p, x):
        return jnp.exp(m.val) * hm.inner(u.grad, p.grad)

    bc = hm.DirichletBC(Vu, lambda x: x[1], bdr_attributes=[1, 3])
    pde = hm.PDEVariationalProblem([Vu, Vm, Vu], pde_varf, bc,
                                   bc.homogeneous(), is_fwd_linear=True)
"""

from . import _jaxconfig          # noqa: F401  (must precede any jax import)
from . import _petsc              # noqa: F401  (must precede any mfem import)
from .version import __version__, version_info

from .common import *                 # noqa: F401,F403
from .common import __all__ as _common_all
from .algorithms import *             # noqa: F401,F403
from .algorithms import __all__ as _alg_all
from .fem import *                    # noqa: F401,F403
from .fem import __all__ as _fem_all
from .modeling import *               # noqa: F401,F403
from .modeling import __all__ as _mod_all
from .forward_uq import *            # noqa: F401,F403
from .forward_uq import __all__ as _uq_all
from .mcmc import *                  # noqa: F401,F403
from .mcmc import __all__ as _mcmc_all

# MFEM's device follows the environment (HIPPYMFEM_HYPRE_DEVICE=1 on a GPU build), so
# a script that sets the variable and imports hippymfem first needs no other call.
from .config import config  # noqa: E402  (every knob, in one object)
from .common.mfemconfig import auto_configure_device as _auto_configure_device  # noqa: E402

_auto_configure_device()
from .utils import nb                 # noqa: F401  (plotting helpers for notebooks)

#: The UFL-flavoured helpers of :mod:`hippymfem.fem.jaxops` (``inner``, ``dot``, ``div``,
#: ...).  Listed here so ``hm.inner`` and ``from hippymfem import *`` work, but resolved
#: lazily by ``__getattr__`` below, so that ``import hippymfem`` does not import JAX
#: and bring up a backend when the residual-density route is not used.
_JAX_NAMES = ("inner", "dot", "div", "tr", "sym", "skew", "Identity", "outer", "cross",
              "nabla_grad", "sqrt", "exp", "ln", "log", "norm2")
_KERNEL_NAMES = ("QuadratureKernel", "BoundaryKernel", "GroupKernel", "Field",
                 "set_device")

__all__ = (["__version__", "version_info", "config"]
           + list(_common_all) + list(_alg_all) + list(_fem_all)
           + list(_mod_all) + list(_uq_all) + list(_mcmc_all)
           + list(_JAX_NAMES))


def __getattr__(name):
    """Expose the JAX-dependent layers lazily (PEP 562).

    Uses ``importlib.import_module`` rather than ``from .fem import jaxops``, which
    asks the parent package for the attribute first, re-enters this function (and
    ``fem``'s) and recurses without end.
    """
    if name in _KERNEL_NAMES:
        import importlib

        return getattr(importlib.import_module("hippymfem.fem.kernel"), name)
    if name in _JAX_NAMES:
        import importlib

        return getattr(importlib.import_module("hippymfem.fem.jaxops"), name)
    raise AttributeError("module %r has no attribute %r" % (__name__, name))
