# Copyright (c) 2026, Peng Chen, Georgia Institute of Technology.
# This file is part of hIPPyMFEM, free software under the GNU General Public
# License version 2.0 dated June 1991 (GPL-2.0-only); see the files LICENSE and
# COPYRIGHT.
"""AD element kernels against MFEM's own integrators.

Every block the inverse problem needs is generated by differentiating a
pointwise residual density.  This compares those blocks against hand-written
MFEM integrators on the *same* integration rule, where an exact match is the
only acceptable answer.

Run with ``mpirun -n N python -m hippymfem.test.test_kernels``.
"""

import numpy as np
from mpi4py import MPI

import mfem.par as mfem
import jax.numpy as jnp

import hippymfem as hp
from hippymfem.fem.spaces import FunctionSpace
from hippymfem.fem.elementbatch import MeshBatches
from hippymfem.fem.kernel import QuadratureKernel
from hippymfem.fem.assemble import assemble_matrix, assemble_vector
from hippymfem.fem.jaxops import div, inner, sym
from hippymfem.modeling.variables import ADJOINT, PARAMETER, STATE
from hippymfem.common.parvector import ParVector

COMM = MPI.COMM_WORLD
RANK = COMM.rank
NP = COMM.size
FAILS = []


def check(name, ok, detail=""):
    if RANK == 0:
        print("  [%s] %s %s" % ("ok  " if ok else "FAIL", name, detail), flush=True)
    if not ok:
        FAILS.append(name)


def relerr_op(A, B, template):
    """Relative difference of two HypreParMatrix actions on a random vector."""
    x = ParVector(COMM, A.Width())
    y1 = ParVector(COMM, A.Height())
    y2 = ParVector(COMM, A.Height())
    hp.parRandom.set_seed(99)
    hp.parRandom.normal(1.0, x)
    A.Mult(x.hypre, y1.hypre)
    B.Mult(x.hypre, y2.hypre)
    n = y1.norm("l2")
    y2.axpy(-1.0, y1)
    return y2.norm("l2") / max(n, 1e-300)


def make_mesh(kind, n=6):
    if kind == "tri":
        m = mfem.Mesh.MakeCartesian2D(n, n, mfem.Element.TRIANGLE)
    elif kind == "quad":
        m = mfem.Mesh.MakeCartesian2D(n, n, mfem.Element.QUADRILATERAL)
    elif kind == "tet":
        m = mfem.Mesh.MakeCartesian3D(n, n, n, mfem.Element.TETRAHEDRON)
    elif kind == "hex":
        m = mfem.Mesh.MakeCartesian3D(n, n, n, mfem.Element.HEXAHEDRON)
    else:
        raise ValueError(kind)
    return mfem.ParMesh(COMM, m)


def _split_mesh_n():
    """Cells a side of a hexahedral mesh with at least 512 elements on every rank, twice
    the chunk planner's floor, so the planner can split a rank's batch."""
    n = 10
    while n ** 3 < 512 * NP:
        n += 1
    return n


# --------------------------------------------------------------------- tests
def test_mass_and_diffusion(kind, order_u, order_m, qdeg=None):
    """A = d2R/dp du for r = exp(m) grad u . grad p + m^2 u p."""
    pmesh = make_mesh(kind, 4 if kind in ("tet", "hex") else 6)
    Vu = FunctionSpace.H1(pmesh, order_u)
    Vm = FunctionSpace.H1(pmesh, order_m)
    spaces = [Vu, Vm, Vu]
    qdeg = qdeg or (2 * max(order_u, order_m) + 2)
    batches = MeshBatches(pmesh, qdeg)

    def varf(u, m, p, x):
        return jnp.exp(m.val) * inner(u.grad, p.grad) + (m.val ** 2) * u.val * p.val

    K = QuadratureKernel(varf, spaces, batches)

    mgf = mfem.ParGridFunction(Vm.fes)
    mcoef = _PyC(lambda x: 0.3 * np.sin(3.0 * x[0]) + 0.2 * x[-1])
    mgf.ProjectCoefficient(mcoef)
    mvec = Vm.from_gridfunction(mgf)

    loc = [
        (Vu.local_values(Vu.vector())),
        Vm.local_values(mvec),
        (Vu.local_values(Vu.vector())),
    ]
    mats = K.element_matrices(ADJOINT, STATE, loc)
    A = assemble_matrix(Vu, Vu, batches.groups, mats, pmesh.GetNE())

    # MFEM reference on the same rule.  The coefficients must be functions of
    # the *interpolant* of m in Vm, which is what the kernel sees; using exp of
    # the exact function instead compares two different discretizations and
    # differs by the interpolation error (~1e-2 at P1 on this mesh).
    ir = batches.groups[0].ir
    expm = _GfC(mgf, np.exp)
    m2 = _GfC(mgf, lambda t: t * t)
    ref = mfem.ParBilinearForm(Vu.fes)
    d = mfem.DiffusionIntegrator(expm)
    d.SetIntRule(ir)
    mm = mfem.MassIntegrator(m2)
    mm.SetIntRule(ir)
    ref.AddDomainIntegrator(d)
    ref.AddDomainIntegrator(mm)
    ref.Assemble()
    ref.Finalize()
    R = ref.ParallelAssemble()

    e = relerr_op(A, R, Vu)
    check("A (%s, Pu=%d, Pm=%d) vs Diffusion(exp m)+Mass(m^2)" % (kind, order_u, order_m),
          e < 1e-13, "(%.2e)" % e)
    return pmesh, Vu, Vm, batches, K, loc, mvec


def test_symmetry_and_transpose():
    """A^T must equal d2R/du dp; C and W blocks must have exact layouts."""
    pmesh = make_mesh("tri", 6)
    Vu = FunctionSpace.H1(pmesh, 2)
    Vm = FunctionSpace.H1(pmesh, 1)
    batches = MeshBatches(pmesh, 6)

    def varf(u, m, p, x):
        # deliberately nonsymmetric in u and with u-m coupling
        return (jnp.exp(m.val) * inner(u.grad, p.grad)
                + u.val ** 3 * m.val * p.val
                + u.grad[0] * p.val)

    K = QuadratureKernel(varf, [Vu, Vm, Vu], batches)

    hp.parRandom.set_seed(5)
    uv, mv, pv = Vu.vector(), Vm.vector(), Vu.vector()
    for v in (uv, mv, pv):
        hp.parRandom.normal(0.4, v)
    loc = [
        Vu.local_values(uv),
        Vm.local_values(mv),
        Vu.local_values(pv),
    ]
    NE = pmesh.GetNE()

    A = assemble_matrix(Vu, Vu, batches.groups,
                        K.element_matrices(ADJOINT, STATE, loc), NE)
    At = assemble_matrix(Vu, Vu, batches.groups,
                         K.element_matrices(STATE, ADJOINT, loc), NE)
    x = ParVector(COMM, A.Width())
    y = ParVector(COMM, A.Height())
    z = ParVector(COMM, A.Height())
    hp.parRandom.normal(1.0, x)
    A.MultTranspose(x.hypre, y.hypre)
    At.Mult(x.hypre, z.hypre)
    e = z.copy().axpy(-1.0, y).norm("l2") / max(y.norm("l2"), 1e-300)
    check("d2R/du dp == (d2R/dp du)^T", e < 1e-13, "(%.2e)" % e)

    # C is rectangular: rows = adjoint space, cols = parameter space
    C = assemble_matrix(Vu, Vm, batches.groups,
                        K.element_matrices(ADJOINT, PARAMETER, loc), NE)
    check("C shape", C.GetGlobalNumRows() == Vu.GlobalTrueVSize()
          and C.GetGlobalNumCols() == Vm.GlobalTrueVSize(),
          "(%d x %d)" % (C.GetGlobalNumRows(), C.GetGlobalNumCols()))

    # Wum^T == Wmu
    Wum = assemble_matrix(Vu, Vm, batches.groups,
                          K.element_matrices(STATE, PARAMETER, loc), NE)
    Wmu = assemble_matrix(Vm, Vu, batches.groups,
                          K.element_matrices(PARAMETER, STATE, loc), NE)
    xm = ParVector(COMM, Wum.Width())
    hp.parRandom.normal(1.0, xm)
    yu = ParVector(COMM, Wum.Height())
    Wum.Mult(xm.hypre, yu.hypre)
    xu = ParVector(COMM, Wmu.Width())
    hp.parRandom.normal(1.0, xu)
    ym = ParVector(COMM, Wmu.Height())
    Wmu.Mult(xu.hypre, ym.hypre)
    lhs = yu.inner(xu)
    rhs = ym.inner(xm)
    check("W_um and W_mu are transposes",
          abs(lhs - rhs) <= 1e-11 * max(1.0, abs(lhs)), "(%.6e vs %.6e)" % (lhs, rhs))

    # Wuu, Wmm symmetric
    for (i, j, V, nm) in ((STATE, STATE, Vu, "W_uu"), (PARAMETER, PARAMETER, Vm, "W_mm")):
        W = assemble_matrix(V, V, batches.groups,
                            K.element_matrices(i, j, loc), NE)
        a = ParVector(COMM, W.Width())
        b = ParVector(COMM, W.Width())
        hp.parRandom.normal(1.0, a)
        hp.parRandom.normal(1.0, b)
        Wa = ParVector(COMM, W.Height())
        Wb = ParVector(COMM, W.Height())
        W.Mult(a.hypre, Wa.hypre)
        W.Mult(b.hypre, Wb.hypre)
        s = abs(Wa.inner(b) - Wb.inner(a)) / max(abs(Wa.inner(b)), 1e-300)
        check("%s symmetric" % nm, s < 1e-12, "(%.2e)" % s)


def test_symmetry_probe():
    """``symmetric_jacobian="auto"`` must read the symmetry off the assembled matrix.

    A false positive would send the adjoint solve through the wrong operator, so the
    probe is checked on a residual that is self-adjoint in the state and on the same
    residual with an advective term, which is not.  It must also leave the library's
    random stream where it found it: the probe draws its own vectors, and a prior
    sample taken after one has to be the sample that would have been taken without.
    """
    pmesh = make_mesh("quad", 6)
    Vu = FunctionSpace.H1(pmesh, 2)
    Vm = FunctionSpace.H1(pmesh, 1)
    bc = hp.DirichletBC(Vu, lambda x: x[1], bdr_attributes="all")

    def sym_varf(u, m, p, x):
        return jnp.exp(m.val) * inner(u.grad, p.grad)

    def adv_varf(u, m, p, x):
        return jnp.exp(m.val) * inner(u.grad, p.grad) + u.grad[0] * p.val

    for name, varf, expected in (("self-adjoint residual", sym_varf, True),
                                 ("residual with an advective term", adv_varf, False)):
        pde = hp.PDEVariationalProblem([Vu, Vm, Vu], varf, bc, bc.homogeneous(),
                                       is_fwd_linear=True)
        x = [pde.generate_state(), pde.generate_parameter(), pde.generate_adjoint()]
        A = pde._block(ADJOINT, STATE, x, test_ess=pde.bc0.ess_tdof, diag_policy="one")
        got = pde._probe_symmetry(A)
        check("symmetry probe on a %s" % name, got is expected, "(said %s)" % got)

    # the probe must not consume words from the shared stream
    before, after = Vu.vector(), Vu.vector()
    hp.parRandom.set_seed(11)
    hp.parRandom.normal(1.0, before)
    pde._probe_symmetry(A)
    hp.parRandom.set_seed(11)
    hp.parRandom.normal(1.0, after)
    d = after.copy().axpy(-1.0, before).norm("l2")
    check("the symmetry probe leaves parRandom's stream alone", d == 0.0, "(%.2e)" % d)


def test_residual_vector():
    """Residual vector vs an MFEM LinearForm, and consistency with the Jacobian."""
    pmesh = make_mesh("quad", 6)
    Vu = FunctionSpace.H1(pmesh, 1)
    Vm = FunctionSpace.H1(pmesh, 1)
    batches = MeshBatches(pmesh, 4)

    # linear problem: r = grad u . grad p - f p  =>  dR/dp = A u - b
    def varf(u, m, p, x):
        return inner(u.grad, p.grad) - (1.0 + x[0]) * p.val

    K = QuadratureKernel(varf, [Vu, Vm, Vu], batches)
    NE = pmesh.GetNE()
    zu, zm = Vu.vector(), Vm.vector()
    loc0 = [Vu.local_values(zu),
            Vm.local_values(zm),
            Vu.local_values(zu)]
    r0 = assemble_vector(Vu, batches.groups,
                         K.element_vectors(ADJOINT, loc0), NE)

    # at u = 0 the residual is -b
    ir = batches.groups[0].ir
    lf = mfem.ParLinearForm(Vu.fes)
    fc = _PyC(lambda x: -(1.0 + x[0]))
    di = mfem.DomainLFIntegrator(fc)
    di.SetIntRule(ir)
    lf.AddDomainIntegrator(di)
    lf.Assemble()
    b = Vu.vector()
    bhv = lf.ParallelAssemble()          # must stay referenced: see common.to_numpy
    b.array[:] = hp.to_numpy(bhv, copy=False)
    e = r0.copy().axpy(-1.0, b).norm("l2") / max(b.norm("l2"), 1e-300)
    check("residual at u=0 vs DomainLFIntegrator", e < 1e-13, "(%.2e)" % e)

    # residual is affine: r(u) = A u + r(0)
    hp.parRandom.set_seed(21)
    uv = Vu.vector()
    hp.parRandom.normal(1.0, uv)
    loc1 = [Vu.local_values(uv), loc0[1], loc0[2]]
    r1 = assemble_vector(Vu, batches.groups, K.element_vectors(ADJOINT, loc1), NE)
    A = assemble_matrix(Vu, Vu, batches.groups,
                        K.element_matrices(ADJOINT, STATE, loc1), NE)
    Au = Vu.vector()
    A.Mult(uv.hypre, Au.hypre)
    pred = Au.copy().axpy(1.0, r0)
    e = pred.copy().axpy(-1.0, r1).norm("l2") / max(r1.norm("l2"), 1e-300)
    check("residual consistent with Jacobian (linear form)", e < 1e-12, "(%.2e)" % e)


def test_vector_elasticity():
    """Vector-valued state: linear elasticity vs MFEM's ElasticityIntegrator."""
    pmesh = make_mesh("tri", 5)
    dim = pmesh.Dimension()
    Vu = FunctionSpace.H1(pmesh, 2, vdim=dim)
    Vm = FunctionSpace.H1(pmesh, 1)
    batches = MeshBatches(pmesh, 6)
    lam, mu = 1.7, 0.9

    def varf(u, m, p, x):
        eu = sym(u.grad)
        ep = sym(p.grad)
        return 2.0 * mu * inner(eu, ep) + lam * div(u.grad) * div(p.grad)

    K = QuadratureKernel(varf, [Vu, Vm, Vu], batches)
    NE = pmesh.GetNE()
    loc = [(Vu.local_values(Vu.vector())),
           Vm.local_values(Vm.vector()),
           (Vu.local_values(Vu.vector()))]
    A = assemble_matrix(Vu, Vu, batches.groups,
                        K.element_matrices(ADJOINT, STATE, loc), NE)

    ir = batches.groups[0].ir
    lc = mfem.ConstantCoefficient(lam)
    mc = mfem.ConstantCoefficient(mu)
    ei = mfem.ElasticityIntegrator(lc, mc)
    ei.SetIntRule(ir)
    ref = mfem.ParBilinearForm(Vu.fes)
    ref.AddDomainIntegrator(ei)
    ref.Assemble()
    ref.Finalize()
    Rm = ref.ParallelAssemble()
    e = relerr_op(A, Rm, Vu)
    check("vector elasticity vs ElasticityIntegrator", e < 1e-12, "(%.2e)" % e)


def test_convection():
    """Nonsymmetric convection term vs ConvectionIntegrator."""
    pmesh = make_mesh("tri", 6)
    Vu = FunctionSpace.H1(pmesh, 2)
    Vm = FunctionSpace.H1(pmesh, 1)
    batches = MeshBatches(pmesh, 6)
    vel = np.array([0.7, -1.3])

    def varf(u, m, p, x):
        return jnp.dot(jnp.array(vel), u.grad) * p.val

    K = QuadratureKernel(varf, [Vu, Vm, Vu], batches)
    NE = pmesh.GetNE()
    loc = [(Vu.local_values(Vu.vector())),
           Vm.local_values(Vm.vector()),
           (Vu.local_values(Vu.vector()))]
    A = assemble_matrix(Vu, Vu, batches.groups,
                        K.element_matrices(ADJOINT, STATE, loc), NE)

    ir = batches.groups[0].ir
    vc = mfem.VectorConstantCoefficient(mfem.Vector(vel))
    ci = mfem.ConvectionIntegrator(vc)
    ci.SetIntRule(ir)
    ref = mfem.ParBilinearForm(Vu.fes)
    ref.AddDomainIntegrator(ci)
    ref.Assemble()
    ref.Finalize()
    e = relerr_op(A, ref.ParallelAssemble(), Vu)
    check("convection vs ConvectionIntegrator", e < 1e-12, "(%.2e)" % e)


def test_finite_difference_consistency():
    """Second and third derivative blocks against finite differences of the first."""
    pmesh = make_mesh("tri", 5)
    Vu = FunctionSpace.H1(pmesh, 2)
    Vm = FunctionSpace.H1(pmesh, 1)
    batches = MeshBatches(pmesh, 7)

    def varf(u, m, p, x):
        return (jnp.exp(m.val) * inner(u.grad, p.grad)
                + u.val ** 3 * p.val * jnp.sin(m.val))

    K = QuadratureKernel(varf, [Vu, Vm, Vu], batches)
    NE = pmesh.GetNE()
    hp.parRandom.set_seed(13)
    uv, mv, pv = Vu.vector(), Vm.vector(), Vu.vector()
    for v in (uv, mv, pv):
        hp.parRandom.normal(0.3, v)
    du, dm = Vu.vector(), Vm.vector()
    hp.parRandom.normal(1.0, du)
    hp.parRandom.normal(1.0, dm)

    def loc_of(u, m, p):
        return [Vu.local_values(u),
                Vm.local_values(m),
                Vu.local_values(p)]

    # d/du of dR/dp in direction du  vs  (dR/dp(u+h du) - dR/dp(u-h du)) / 2h
    A = assemble_matrix(Vu, Vu, batches.groups,
                        K.element_matrices(ADJOINT, STATE, loc_of(uv, mv, pv)), NE)
    exact = Vu.vector()
    A.Mult(du.hypre, exact.hypre)
    h = 1e-6
    up = uv.copy().axpy(h, du)
    um = uv.copy().axpy(-h, du)
    rp = assemble_vector(Vu, batches.groups,
                         K.element_vectors(ADJOINT, loc_of(up, mv, pv)), NE)
    rm = assemble_vector(Vu, batches.groups,
                         K.element_vectors(ADJOINT, loc_of(um, mv, pv)), NE)
    fd = rp.copy().axpy(-1.0, rm).scale(1.0 / (2 * h))
    e = fd.copy().axpy(-1.0, exact).norm("l2") / max(exact.norm("l2"), 1e-300)
    check("A == FD of residual in u", e < 1e-7, "(%.2e)" % e)

    # C in direction dm
    Cm = assemble_matrix(Vu, Vm, batches.groups,
                         K.element_matrices(ADJOINT, PARAMETER, loc_of(uv, mv, pv)), NE)
    exactC = Vu.vector()
    Cm.Mult(dm.hypre, exactC.hypre)
    mp_ = mv.copy().axpy(h, dm)
    mm_ = mv.copy().axpy(-h, dm)
    rp = assemble_vector(Vu, batches.groups,
                         K.element_vectors(ADJOINT, loc_of(uv, mp_, pv)), NE)
    rm = assemble_vector(Vu, batches.groups,
                         K.element_vectors(ADJOINT, loc_of(uv, mm_, pv)), NE)
    fd = rp.copy().axpy(-1.0, rm).scale(1.0 / (2 * h))
    e = fd.copy().axpy(-1.0, exactC).norm("l2") / max(exactC.norm("l2"), 1e-300)
    check("C == FD of residual in m", e < 1e-7, "(%.2e)" % e)

    # third derivative: d3R/dp du dm [du, dm] vs FD of A in m
    thirds = K.element_third(
        ADJOINT, STATE, PARAMETER, loc_of(uv, mv, pv),
        Vu.local_values(du),
        Vm.local_values(dm),
    )
    t = assemble_vector(Vu, batches.groups, thirds, NE)
    Ap = assemble_matrix(Vu, Vu, batches.groups,
                         K.element_matrices(ADJOINT, STATE, loc_of(uv, mp_, pv)), NE)
    Am = assemble_matrix(Vu, Vu, batches.groups,
                         K.element_matrices(ADJOINT, STATE, loc_of(uv, mm_, pv)), NE)
    a1, a2 = Vu.vector(), Vu.vector()
    Ap.Mult(du.hypre, a1.hypre)
    Am.Mult(du.hypre, a2.hypre)
    fd = a1.copy().axpy(-1.0, a2).scale(1.0 / (2 * h))
    e = fd.copy().axpy(-1.0, t).norm("l2") / max(t.norm("l2"), 1e-300)
    check("third derivative == FD of A in m", e < 1e-6, "(%.2e)" % e)


def test_bc_elimination():
    """Essential-dof elimination follows the documented diagonal policies."""
    from hippymfem.fem.bcs import BCSet, DirichletBC

    pmesh = make_mesh("tri", 6)
    Vu = FunctionSpace.H1(pmesh, 1)
    Vm = FunctionSpace.H1(pmesh, 1)
    batches = MeshBatches(pmesh, 4)

    # u^2 p makes W_uu genuinely nonzero, so the diagonal policy is observable.
    def varf(u, m, p, x):
        return inner(u.grad, p.grad) + u.val ** 2 * p.val

    K = QuadratureKernel(varf, [Vu, Vm, Vu], batches)
    NE = pmesh.GetNE()
    hp.parRandom.set_seed(77)
    uv, pv = Vu.vector(), Vu.vector()
    hp.parRandom.normal(1.0, uv)
    hp.parRandom.normal(1.0, pv)
    loc = [(Vu.local_values(uv)),
           (Vm.local_values(Vm.vector())),
           (Vu.local_values(pv))]

    bc0 = BCSet([DirichletBC(Vu, None, bdr_attributes=[1, 3])])
    nglob = COMM.allreduce(len(bc0.ess))
    check("found essential dofs", nglob > 0, "(%d local-sum)" % nglob)

    A = assemble_matrix(Vu, Vu, batches.groups,
                        K.element_matrices(ADJOINT, STATE, loc), NE,
                        test_ess=bc0.ess_tdof, diag_policy="one")
    d = hp.get_diagonal(A, comm=COMM)
    ok = True
    if len(bc0.ess):
        ok = np.allclose(d.array[bc0.ess], 1.0)
    check("A: unit diagonal on essential dofs", COMM.allreduce(int(ok), op=MPI.MIN) == 1)

    # e_i for an essential dof must be mapped to itself
    if len(bc0.ess):
        e = Vu.vector()
        e.array[bc0.ess[0]] = 1.0
    else:
        e = Vu.vector()
    out = Vu.vector()
    A.Mult(e.hypre, out.hypre)
    diff = out.copy().axpy(-1.0, e).norm("l2")
    check("A acts as identity on essential block", diff < 1e-13, "(%.2e)" % diff)

    W = assemble_matrix(Vu, Vu, batches.groups,
                        K.element_matrices(STATE, STATE, loc), NE,
                        test_ess=bc0.ess_tdof, diag_policy="zero")
    dz = hp.get_diagonal(W, comm=COMM)
    ok = True
    if len(bc0.ess):
        ok = np.allclose(dz.array[bc0.ess], 0.0)
    check("W_uu: zero diagonal on essential dofs",
          COMM.allreduce(int(ok), op=MPI.MIN) == 1)

    C = assemble_matrix(Vu, Vm, batches.groups,
                        K.element_matrices(ADJOINT, PARAMETER, loc), NE,
                        test_ess=bc0.ess_tdof)
    xm = Vm.vector()
    hp.parRandom.set_seed(4)
    hp.parRandom.normal(1.0, xm)
    yu = Vu.vector()
    C.Mult(xm.hypre, yu.hypre)
    ok = True
    if len(bc0.ess):
        ok = np.allclose(yu.array[bc0.ess], 0.0)
    check("C: essential rows eliminated", COMM.allreduce(int(ok), op=MPI.MIN) == 1)


def test_host_batch():
    """On the host the kernels step through the batch ``host_batch`` elements at a time
    inside the compiled program; the element arrays must agree with the whole-batch map
    whatever the step, one that does not divide the batch included.  Long steps have
    matched it bit for bit, short ones (7 elements) round differently by an ulp, so the
    test allows round-off.  The setting is read at every call."""
    if RANK == 0:
        print("stepping through the batch on the host")
    from hippymfem.fem import kernel as kern

    if kern.on_gpu():
        check("host stepping (skipped: the kernels run on a GPU)", True)
        return
    pmesh = make_mesh("tet", 6)
    Vu = FunctionSpace.H1(pmesh, 2)
    Vm = FunctionSpace.H1(pmesh, 1)
    batches = MeshBatches(pmesh, 4)
    K = QuadratureKernel(lambda u, m, p, x: (jnp.exp(m.val) * inner(u.grad, p.grad)
                                             + u.val ** 3 * p.val),
                         [Vu, Vm, Vu], batches)
    rng = np.random.default_rng(2)
    loc = [rng.standard_normal(Vu.local_values(Vu.vector()).size),
           rng.standard_normal(Vm.local_values(Vm.vector()).size),
           rng.standard_normal(Vu.local_values(Vu.vector()).size)]
    dirs = [(loc[0] * 0.5, loc[1] * 2.0, None), (None, loc[1], loc[2])]

    def arrays():
        mats = K.element_matrices(ADJOINT, STATE, loc)
        vec = K.element_vectors(PARAMETER, loc)
        third = K.element_third(STATE, STATE, PARAMETER, loc, loc[0], loc[1])
        fused = K.element_third_dir(STATE, loc, dirs, [0.3, -1.1])
        return [np.asarray(a) for part in (mats, vec, third, fused) for a in part]

    saved = kern.HOST_BATCH
    try:
        ref = None
        worst = 0.0
        for batch in (0, 2048, 100, 7):
            kern.HOST_BATCH = batch
            got = arrays()
            if ref is None:
                ref = got
                continue
            for a, b in zip(ref, got):
                worst = max(worst, float(np.abs(a - b).max() / max(np.abs(a).max(), 1e-300)))
    finally:
        kern.HOST_BATCH = saved
    ne = pmesh.GetNE()
    check("steps of 2048, 100 and 7 elements give the whole-batch arrays (%d elements)" % ne,
          worst <= 1e-15, "(max rel %.1e)" % worst)
    hp.config.host_batch = 64
    ok = kern.HOST_BATCH == 64
    hp.config.host_batch = saved
    check("hm.config.host_batch sets it", ok and kern.HOST_BATCH == saved)


def test_host_chunk_budget():
    """On the host the chunk planner plans against the node's memory, not the whole group.

    Without a budget it takes the group in one launch, which is right until a rank holds
    a few hundred thousand elements: at 524288 P2 hexahedra a rank a 256^3 run was killed
    by the OOM killer before its first assembly.  The budget is this rank's share of
    ``MemAvailable``, so the same code chunks when memory is short and does not when it
    is not.  ``HIPPYMFEM_HOST_MEM_FRACTION=0`` restores the old behaviour.
    """
    if RANK == 0:
        print("the host chunk planner's budget")
    from hippymfem.fem import kernel as kern

    # more than the planner's floor of 256 elements a launch on every rank, so a split
    # is possible (10^3 elements on 4 ranks left 250 a rank)
    pmesh = make_mesh("hex", _split_mesh_n())
    Vu = FunctionSpace.H1(pmesh, 2)
    Vm = FunctionSpace.H1(pmesh, 1)
    batches = MeshBatches(pmesh, 6)
    K = QuadratureKernel(lambda u, m, p, x: jnp.exp(m.val) * inner(u.grad, p.grad),
                         [Vu, Vm, Vu], batches)
    loc = [Vu.local_values(Vu.vector()), Vm.local_values(Vm.vector()),
           Vu.local_values(Vu.vector())]
    ne = pmesh.GetNE()
    gk = K.group_kernels[0]
    d = kern.device()

    def forget():
        for g in K.group_kernels:
            g._chunk.clear()

    saved = kern.HOST_MEM_FRACTION
    try:
        kern.HOST_MEM_FRACTION = 0.0
        forget()
        whole = kern._free_budget(d)
        n_whole = gk._plan(ne, d, 1.0) if whole is not None else ne
        check("with no host budget the group is taken whole", whole is None and n_whole == ne,
              "(%d elements in one launch)" % ne)

        # a budget of a few megabytes a rank has to split this group
        kern.HOST_MEM_FRACTION = 1e-6
        forget()
        small = kern._free_budget(d)
        n_small = gk._plan(ne, d, 1.0)
        check("a small host budget splits it", small is not None and 0 < n_small < ne,
              "(budget %.1f MiB -> %d of %d elements a launch)"
              % ((small or 0) / 2 ** 20, n_small, ne))

        # and the split assembly is the same matrix as the unsplit one
        A_split = assemble_matrix(Vu, Vu, batches.groups,
                                  K.element_matrices_or_chunks(ADJOINT, STATE, loc), ne)
        kern.HOST_MEM_FRACTION = 0.0
        forget()
        A_whole = assemble_matrix(Vu, Vu, batches.groups,
                                  K.element_matrices(ADJOINT, STATE, loc), ne)
        v = Vu.vector()
        hp.parRandom.set_seed(7)
        hp.parRandom.normal(1.0, v)
        y1, y2 = Vu.vector(), Vu.vector()
        A_split.Mult(v.hypre, y1.hypre)
        A_whole.Mult(v.hypre, y2.hypre)
        e = y1.copy().axpy(-1.0, y2).norm("linf") / max(y2.norm("linf"), 1e-300)
        check("a chunked host assembly is the unchunked one", e < 1e-14, "(rel %.2e)" % e)
    finally:
        kern.HOST_MEM_FRACTION = saved
        forget()

    n = kern._node_ranks()
    check("the ranks on the node are read from the launcher", n >= 1, "(%d)" % n)


def test_chunk_plan_per_pass():
    """A pass's chunk size is its own, and the unsplit route knows when it cannot fit.

    XLA's analysis sizes each pass from the compiled program, so a gradient pass may fit
    whole where a Hessian pass of the same weight must split.  Kept under the weight, as
    the estimate is, the gradient's answer reached :meth:`will_chunk`, and a 128^3
    assembly on two L40S took the unsplit route with a batch whose joined output did not
    fit, then halved its chunk down to five elements before failing.
    """
    import jax

    from hippymfem.fem import kernel as kern

    pmesh = make_mesh("hex", _split_mesh_n())
    Vu = FunctionSpace.H1(pmesh, 2)
    Vm = FunctionSpace.H1(pmesh, 1)
    batches = MeshBatches(pmesh, 6)
    K = QuadratureKernel(lambda u, m, p, x: jnp.exp(m.val) * inner(u.grad, p.grad),
                         [Vu, Vm, Vu], batches)
    loc = [Vu.local_values(Vu.vector()), Vm.local_values(Vm.vector()),
           Vu.local_values(Vu.vector())]
    ne = pmesh.GetNE()
    gk = K.group_kernels[0]
    d = kern.device()

    def forget():
        for g in K.group_kernels:
            g._chunk.clear()

    saved = (kern._free_budget, kern.CHUNK_PLAN, kern.ELEMENT_CHUNK)
    try:
        # a budget the estimate splits a Hessian pass under and a gradient pass fits in
        kern._free_budget = lambda dev: 200 * 2 ** 20
        kern.CHUNK_PLAN = "xla"
        forget()
        before = K.will_chunk()
        K.element_vectors(ADJOINT, loc)
        grad_n = gk._chunk.get((d, "plan", gk.grad_block(ADJOINT)._raw, True))
        after = K.will_chunk()
        check("a gradient pass that fits whole leaves the Hessian's route alone",
              before and after and grad_n == gk.group.ne,
              "(will_chunk %s then %s; gradient chunk %s of %d)"
              % (before, after, grad_n, gk.group.ne))

        A_split = assemble_matrix(Vu, Vu, batches.groups,
                                  K.element_matrices_or_chunks(ADJOINT, STATE, loc), ne)
        hess = gk.hess_block(ADJOINT, STATE)
        n_xla = gk._chunk.get((d, "plan", hess._raw, False))
        n_est = gk._plan(gk.group.ne, d, hess._weight, announce=False, remember=False)
        probe = kern._analysed_per_element(
            hess._slot_raws, (gk.gather(loc),) + tuple(gk.mapped()) + (kern._params(()),),
            gk._axes(), 64)
        check("the analysed Hessian chunk is never smaller than the estimate",
              n_xla is not None and n_xla >= n_est
              and (probe is None or n_xla > n_est or n_xla == gk.group.ne),
              "(%s against %d of %d; analysis %s)"
              % (n_xla, n_est, gk.group.ne, "none" if probe is None else
                 "%.0f kB an element" % (probe[0] / 1e3)))

        kern._free_budget = lambda dev: None
        forget()
        A_whole = assemble_matrix(Vu, Vu, batches.groups,
                                  K.element_matrices(ADJOINT, STATE, loc), ne)
        v = Vu.vector()
        hp.parRandom.set_seed(7)
        hp.parRandom.normal(1.0, v)
        y1, y2 = Vu.vector(), Vu.vector()
        A_split.Mult(v.hypre, y1.hypre)
        A_whole.Mult(v.hypre, y2.hypre)
        e = y1.copy().axpy(-1.0, y2).norm("linf") / max(y2.norm("linf"), 1e-300)
        check("the analysed split assembles the unsplit matrix", e < 1e-14, "(rel %.2e)" % e)

        # the unsplit route, split by a pin, on a device whose free memory cannot hold
        # its joined output twice: one clear error, not a halving down to one element
        real = gk.grad_block(ADJOINT)._raw
        calls = []

        def starved(*a):
            if not isinstance(jax.tree_util.tree_leaves(a)[0], jax.core.Tracer):
                calls.append(1)
                raise RuntimeError("RESOURCE_EXHAUSTED: Out of memory while trying to "
                                   "allocate 4096 bytes.")
            return real(*a)

        kern.ELEMENT_CHUNK = 100
        kern._free_budget = lambda dev: 1024
        forget()
        wrapped = gk._chunked(starved, gk._axes())
        try:
            wrapped(gk.gather(loc), *gk.mapped(), kern._params(()))
            raised = "nothing"
        except MemoryError:
            raised = "MemoryError"
        except Exception as exc:                                  # noqa: BLE001
            raised = type(exc).__name__
        check("a joined output that cannot fit fails at once",
              raised == "MemoryError" and len(calls) == 1,
              "(%s after %d attempts)" % (raised, len(calls)))

        # the streamed route: a chunk over 40 elements does not fit, so the pinned 100
        # is shrunk from what the allocator asked for and the same stretch tried again
        def small_only(*a):
            lead = jax.tree_util.tree_leaves(a)[0]
            if not isinstance(lead, jax.core.Tracer) and lead.shape[0] > 40:
                raise RuntimeError("RESOURCE_EXHAUSTED: Out of memory while trying to "
                                   "allocate 4096 bytes.")
            return real(*a)

        def streamed():
            pass
        streamed._raw = small_only
        streamed._weight = 1
        kern._free_budget = lambda dev: 2 ** 20
        forget()
        dofs = gk.gather(loc)
        pieces = list(gk.in_chunks(streamed, dofs, gk.mapped(streaming=True),
                                   kern._params(())))
        spans = [(a, b) for a, b, _ in pieces]
        joined = np.concatenate([np.asarray(out) for _, _, out in pieces])
        whole = np.asarray(real(dofs, *gk.mapped(), kern._params(())))
        err = np.abs(joined - whole).max() / max(np.abs(whole).max(), 1e-300)
        contiguous = (spans[0][0] == 0 and spans[-1][1] == gk.group.ne
                      and all(spans[k][1] == spans[k + 1][0] for k in range(len(spans) - 1)))
        check("a streamed chunk that does not fit is shrunk and its stretch retried",
              contiguous and max(b - a for a, b in spans) <= 40 and err < 1e-14
              and gk._chunk.get((d, 1)) == max(b - a for a, b in spans),
              "(%d chunks of at most %d, rel %.1e)"
              % (len(spans), max(b - a for a, b in spans), err))
    finally:
        kern._free_budget, kern.CHUNK_PLAN, kern.ELEMENT_CHUNK = saved
        forget()


def test_sliced_geometry():
    """The geometry built here, in element slices, against MFEM's batched call.

    A rank with a few million elements cannot use MFEM's ``GetGeometricFactors``
    (it sizes ``nq*sdim*dim*NE`` with an int), so above that limit the quadrature
    geometry is built from the mesh nodes instead.  The two must agree wherever both
    can run, on a curved mesh as much as a straight one, and the slice size must not
    matter.
    """
    from hippymfem.fem.elementbatch import ElementGroup

    worst = 0.0
    for curved in (False, True):
        pmesh = mfem.ParMesh(COMM, mfem.Mesh.MakeCartesian3D(
            max(2, NP), 2, 2, mfem.Element.HEXAHEDRON))
        if curved:
            pmesh.SetCurvature(2)
            nodes = pmesh.GetNodes().GetDataArray()
            nodes[:] = nodes + 0.01 * np.sin(7.0 * nodes)
        if not pmesh.GetNE():
            continue
        geom = pmesh.GetElementGeometry(0)
        elems = np.arange(pmesh.GetNE())
        ref = ElementGroup(pmesh, geom, elems, 4, batched=True, sliced=False)
        for slice_ne in (0, 3):
            got = ElementGroup(pmesh, geom, elems, 4, batched=True, sliced=True)
            if slice_ne:
                got._geometry_sliced(slice_ne=slice_ne)
            for a in ("Jinv", "detJ", "X", "wdet"):
                r, t = getattr(ref, a), getattr(got, a)
                worst = max(worst, float(np.abs(r - t).max()
                                         / max(np.abs(r).max(), 1e-300)))
    worst = COMM.allreduce(worst, op=MPI.MAX)
    check("sliced geometry matches MFEM's batched factors", worst < 1e-12,
          "(straight and curved, worst rel %.1e)" % worst)


def test_mixed_geometry():
    """A mesh with both triangles and quadrilaterals.

    Sized so that every rank gets elements: MFEM's partitioner **hangs** when a
    mesh has fewer elements than ranks, which is a property of the mesh and not
    of the code under test.
    """
    from .mixed_mesh import write_mixed_mesh

    n = max(8, 4 * NP)
    path = "/tmp/_hippymfem_mixed_n%d.mesh" % n
    if RANK == 0:
        write_mixed_mesh(path, n)
    COMM.Barrier()
    pmesh = mfem.ParMesh(COMM, mfem.Mesh(path, 1, 1))
    Vu = FunctionSpace.H1(pmesh, 1)
    Vm = FunctionSpace.H1(pmesh, 1)
    batches = MeshBatches(pmesh, 4)
    ngeo = COMM.allreduce(pmesh.GetNumGeometries(2), op=MPI.MAX)
    ngroups = COMM.allreduce(len(batches.groups), op=MPI.MAX)
    check("mixed mesh has both geometries", ngeo == 2,
          "(up to %d element groups on a rank)" % ngroups)

    def varf(u, m, p, x):
        return inner(u.grad, p.grad)

    K = QuadratureKernel(varf, [Vu, Vm, Vu], batches)
    NE = pmesh.GetNE()
    loc = [Vu.local_values(Vu.vector()),
           Vm.local_values(Vm.vector()),
           Vu.local_values(Vu.vector())]
    A = assemble_matrix(Vu, Vu, batches.groups,
                        K.element_matrices(ADJOINT, STATE, loc), NE)
    ref = mfem.ParBilinearForm(Vu.fes)
    ref.AddDomainIntegrator(mfem.DiffusionIntegrator())
    ref.Assemble()
    ref.Finalize()
    # P1 diffusion with a constant coefficient is integrated exactly by both
    # rules, so no integration-rule matching is needed here.
    e = relerr_op(A, ref.ParallelAssemble(), Vu)
    check("mixed-geometry diffusion vs DiffusionIntegrator", e < 1e-12, "(%.2e)" % e)


class _GfC(mfem.PyCoefficient):
    """``f(m(x))`` for a grid function ``m``: a function of the interpolant."""

    def __init__(self, gf, fn):
        super(_GfC, self).__init__()
        self.gf = gf
        self.fn = fn

    def Eval(self, T, ip):
        return float(self.fn(self.gf.GetValue(T.ElementNo, ip)))


class _PyC(mfem.PyCoefficient):
    def __init__(self, fn):
        super(_PyC, self).__init__()
        self.fn = fn

    def EvalValue(self, x):
        return float(self.fn(np.asarray(x)))


if __name__ == "__main__":
    mfem.Hypre.Init()
    if RANK == 0:
        print("=" * 74)
        print("hIPPyMFEM kernel tests on %d rank(s)" % NP)
        print("=" * 74)
        print("AD blocks vs MFEM integrators")
    for kind, ou, om in (("tri", 1, 1), ("tri", 2, 1), ("quad", 2, 2),
                         ("tet", 1, 1), ("hex", 2, 1)):
        test_mass_and_diffusion(kind, ou, om)
    if RANK == 0:
        print("structure of the derivative blocks")
    test_symmetry_and_transpose()
    test_symmetry_probe()
    if RANK == 0:
        print("residual vectors")
    test_residual_vector()
    if RANK == 0:
        print("vector-valued and nonsymmetric forms")
    test_vector_elasticity()
    test_convection()
    if RANK == 0:
        print("finite-difference consistency")
    test_finite_difference_consistency()
    test_host_batch()
    if RANK == 0:
        print("boundary conditions")
    test_bc_elimination()
    if RANK == 0:
        print("mixed geometry")
    test_mixed_geometry()
    if RANK == 0:
        print("quadrature geometry")
    test_sliced_geometry()
    if RANK == 0:
        print("host chunk planning")
    test_host_chunk_budget()
    test_chunk_plan_per_pass()
    if RANK == 0:
        print("-" * 74)
        print("FAILURES: %d %s" % (len(FAILS), FAILS if FAILS else ""))
    COMM.Barrier()
    raise SystemExit(1 if FAILS else 0)
